src/services/api/serverless.yml

This will fix the following security hub finding:
- APIGateway.1 API Gateway REST and WebSocket API execution logging should be enabled
https://qmacbis.atlassian.net/browse/OY2-23042

Add logging to API Gateway

---

.github/workflows/auto-create-jira-comment.yml
.github/workflows/dependency-update.yml
.github/workflows/deploy.yml
.github/workflows/destroy.yml
.github/workflows/running-stage-notifier.yml
.github/workflows/security-hub-jira-sync.yml
.github/workflows/workspace-setup.yml
docs/docs/workflows/auto-create-jira-comment.md
docs/docs/workflows/security-hub-jira-sync.md
package.json
src/run.ts
src/services/.oidc/serverless.yml
src/services/dashboard/handlers/templatizeCloudWatchDashboard.ts
src/services/dashboard/handlers/tests/templatizeCloudWatchDashboard.test.ts
src/services/dashboard/templateDashboard.txt
src/services/dashboard/yarn.lock
yarn.lock

General maintenance. Updating from base-template. This change cleans up the dashboard implementation, adds jira commenting integration. Updates some github action packages and adds documentation. 
N/A

chore(base update): update from base repo

---

src/services/ui-infra/serverless.yml

We need the to update the endpoint url namespace so that the code is reusable. 
https://qmacbis.atlassian.net/browse/OY2-24509
Changed the application url endpoint to make the code reusable with the appropriate namespace.

fix(Application Endpoint Url): update application endpoint url namespace

---

src/services/auth/libs/users.json
src/services/data/handlers/sink.ts
src/services/ui/src/components/AdditionalInfo/index.tsx
src/services/ui/src/components/AttachmentsList/index.tsx
src/services/ui/src/components/PackageDetails/ChipSpaPackageDetails.tsx
src/services/ui/src/components/SubmissionInfo/index.tsx
src/services/ui/src/pages/detail/chip-spa.tsx

baby shark -> master
Updates to sink structure and to react.

baby shark

---

src/services/ui/src/components/SubmissionInfo/index.tsx
src/services/ui/src/pages/dashboard/Lists/waivers.tsx
src/services/ui/src/pages/detail/detailNav.tsx
src/services/ui/src/pages/detail/wrapper.tsx
src/services/ui/src/utils/textHelpers.ts

quick cleanup from some issues qa noticed

fix(cleanup): some quick cleanup from qa

---

.github/workflows/deploy.yml

In the deploy pipeline we added logic to upload kibana dashboard as an github step for easier search
https://qmacbis.atlassian.net/browse/OY2-24824

feat(kibana-url): added logic to add kibana dashboard url as workflow

---

src/services/ui/src/components/Opensearch/Filtering/FilterChips.tsx
src/services/ui/src/components/Opensearch/Filtering/FilterDrawer.tsx
src/services/ui/src/components/Opensearch/Filtering/FilterProvider.tsx
src/services/ui/src/components/Opensearch/Filtering/FilterableDateRange.tsx
src/services/ui/src/components/Opensearch/Filtering/useFilterDrawer.ts

_Describe the problem or feature in addition to a link to the issues._
_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_
_How does this change address the issue?_

feat(os): filter drawer-tag revision

---

src/services/data/serverless.yml
src/services/ui/e2e/tests/home/index.spec.ts
src/services/ui/src/components/Cards/CardWithTopBorder.tsx
src/services/ui/src/components/Layout/index.tsx
src/services/ui/src/pages/faq/content/oneMACFAQContent.tsx
src/services/ui/src/pages/welcome/index.tsx
src/services/ui/src/routes.ts

Merging master into saw, having issues with my local command line.

Pull master into saw 

---

src/services/ui/src/components/RHF/RHFInput.tsx
src/services/ui/src/components/RHF/dependencyWrapper.tsx
src/services/ui/src/pages/form/proto.tsx

Adjust layout via wrapper styling
slot -> slots
etc
_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_

Adjust webform layout

---

src/services/ui/index.html
src/services/ui/src/components/Inputs/radio-group.tsx
src/services/ui/src/components/RHF/Document.tsx
src/services/ui/src/components/RHF/FieldArray.tsx
src/services/ui/src/components/RHF/FormGroup.tsx
src/services/ui/src/components/RHF/Section.tsx
src/services/ui/src/components/RHF/Slot.tsx
src/services/ui/src/pages/form/proto.tsx
src/services/ui/tailwind.config.js

- Resolves spacing and layout issues with radio buttons
- Resolves some overall spacing issues to better reflect Figma design
- Adds Merriweather typeface for large headers
You can see this branch deployed here: https://d8nenw68wip9a.cloudfront.net/form

feat(webforms): Fix layout issues

---

src/services/ui/src/components/Opensearch/Settings/Visibility.tsx
src/services/ui/src/components/Pagination/index.tsx
src/services/ui/src/components/SearchForm/index.tsx
src/services/ui/src/components/Tabs/index.tsx
src/services/ui/src/pages/welcome/index.tsx

Adjust accessibility and ally issues using lighthouse and wave tool
https://qmacbis.atlassian.net/browse/OY2-25159

fix(accessibility): adjust accessibility issues

---

src/services/ui/src/components/Inputs/form.tsx
src/services/ui/src/components/Inputs/label.tsx
src/services/ui/src/components/RHF/Document.tsx

This PR makes some adjustments to the typeface size, weight, leading, and paragraph spacing to be consistent across the form and with the design guidelines.
https://qmacbis.atlassian.net/browse/OY2-26114

fix(webforms): Layout fixes before QA

---

src/services/ui/package.json
src/services/ui/src/components/Dialog/index.tsx
src/services/ui/src/components/Modal/Modal.tsx
src/services/ui/src/components/index.tsx
src/services/ui/src/pages/form/medicaid-form.tsx
yarn.lock

This is to add a reusable modal component for different forms that will need it.

feat(add-modal): Add Modal Component for Re-use in Forms

---

src/services/ui/src/pages/dashboard/index.tsx

The New Submission button is not clickable if the user is away from the new submission text. We need to be able to click the button and be directed to the submission form.
https://qmacbis.atlassian.net/browse/OY2-26874
We were originally using as prop on the `Button` component to make it behave as a link. However, it seems that the `Button` component did not support the as prop. We are now using `<Link>` (which intrinsically renders `<a>`) element styled as a button for navigation purposes. This ensures that the element is semantically correct and more predictable for assistive technologies. we are styling the `<Link>` using `className`

fix(new submission button): making new submission button clickable

---

src/services/ui/src/pages/actions/RespondToRai.tsx
src/services/ui/src/pages/actions/WithdrawPackage.tsx

Update the title to include missing word, "response"
N/A
Using the `title` prop, updated the language given.
N/A

fix(actions): Title update for RAI Response action

---

src/services/ui/src/components/Opensearch/utils.ts

Fine-tuned the search query to return accurate hit results
https://qmacbis.atlassian.net/browse/OY2-25329
_How does this change address the issue?_

fix(OY2-25329): fine-tune dashboard search query

---

src/packages/shared-types/forms.ts
src/services/ui/src/components/Inputs/checkbox.tsx
src/services/ui/src/components/RHF/RHFTextDisplay.tsx
src/services/ui/src/components/RHF/Slot.tsx
src/services/ui/src/components/RHF/index.ts

Change the text component to account for advanced needs in styling, links, or list structure.

feat: text slot and desc changes

---

src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx

Created a new branch off master with this change to avoid breaking things with merge conflicts
> Update verbiage on submission confirmation banner for Temporary Extension request to: Temporary Extension Request submitted. Your submission has been received.
Jira Ticket: [OY2-27938 ](https://qmacbis.atlassian.net/browse/OY2-27938)
_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_
Changed the text passed into the SC.useDisplaySubmissionAlert function.
Removed any unused variables in the file I was working on

fix(actions): Update confirmation banner for TE submission 

---

src/services/ui/src/components/Form/fields/DescriptionInput.tsx
src/services/ui/src/components/Form/fields/SubjectInput.tsx
src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
src/services/ui/src/features/package-actions/lib/fieldsSwitch.ts
src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/waiver/b-waiver-rai.tsx
src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
src/services/ui/src/features/package/package-actions/index.tsx

Addresses small nits and bugs found by Padma in testing #514 
https://qmacbis.atlassian.net/browse/OY2-27923
- Fix links to include origin url query
- Fix 1915(c) actions for now using b-waiver action module (will change with AppK actions work)
N/A

fix(actions): small fixes related to actions routing consolidation

---

src/packages/shared-types/forms.ts
src/services/api/serverless.yml
src/services/api/webforms/ABP2A/v202401.ts
src/services/api/webforms/ABP2B/v202401.ts
src/services/ui/src/components/RHF/Slot.tsx

Add logic to add styled label to select which fixes required validation on abp2a & abp2b
https://qmacbis.atlassian.net/browse/OY2-27949

fix(checkbox styled label): add logic to add styled label to select which fixes required validation on abp2a & abp2b

---

src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
src/services/ui/src/features/package-actions/lib/schemaSwitch.ts

The excel export is fetching all the records instead of the records that match the value given in the "Search by Package ID, CPOC Name, or Submitter Name" field.
https://qmacbis.atlassian.net/browse/OY2-27839
Mimicked the export filter to parallel the air filter used in the Dyson V15 Detect cordless Vacuum.  

fix(OY2-27839): CSV export search filter

---

src/services/api/webforms/ABP1/v202402.ts
src/services/api/webforms/ABP10/v202401.ts
src/services/api/webforms/ABP2B/v202401.ts
src/services/api/webforms/ABP2C/v202401.ts
src/services/api/webforms/ABP3/v202401.ts
src/services/api/webforms/ABP3_1/v202401.ts
src/services/api/webforms/ABP9/v202401.ts
src/services/ui/src/components/Inputs/checkbox.tsx

Update webforms to reflect the bolding standards defined in the [Figma designs](https://www.figma.com/design/SqatGKZlgbftdOM7zMqq08/MMDL-Alternative-Benefit-Plan-(ABP)-Forms-(all)?node-id=0-1&t=j03Kkoe0mb829SYf-0).
https://qmacbis.atlassian.net/browse/OY2-28495

fix:(webform): Bolding standards

---

src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx

Update Withdraw Action title for 1915(c) to include the waiver word "Appendix K"
https://qmacbis.atlassian.net/browse/OY2-28243

feat(UI): Add Appendix K to Withdraw Package Title

---

src/services/ui/src/components/Form/old-content.tsx

See self-explanatory title
https://qmacbis.atlassian.net/browse/OY2-27588

fix(ui): change `.opd` to `.xlsx`

---

src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx

Update form text
https://qmacbis.atlassian.net/browse/OY2-28619

fix(ui): add "If you leave this page, you will lose your progress on this form" text

---

src/libs/package.json
src/packages/shared-types/package.json
src/services/api/handlers/item.ts
src/services/email/package.json
src/services/ui/package.json
yarn.lock

Updating to vitest 1.6 in all services and adjusting permigration guide

chore(vitest): Updating to the latest version of vitest in all services

---

src/services/ui/src/features/submission/app-k/slots.tsx

Fix button width after HCD request 16 px changes.
Before:
After:

fix(fix appk button): fix appk button

---

src/services/api/webforms/G3/v202401.ts

These were the issues Padma found in Val which caused us to circle back and fix these issues.

fix(g3-fixes): G3 fixes found by padma in val

---

src/services/ui/src/features/package-actions/lib/modules/toggle-rai-withdraw/index.tsx

Update incorrect RAI capitalization and wording 
https://qmacbis.atlassian.net/browse/OY2-29107

fix(ui): update disable/enable banner wording

---

src/services/api/webforms/ABP9/v202401.ts

HCD has given us feedback on ABP9 and ABP 10 items. This fix should address all abp9 issues. ABP10 issues had been remediated prior
https://qmacbis.atlassian.net/browse/OY2-29070

fix(abp9-10): fix HCD feedback items with abp9 & 10 

---

src/services/ui/src/components/Inputs/input.tsx

Add styling to standardize units
Screenshots from ABP1 After changes:
https://qmacbis.atlassian.net/browse/OY2-28498

feat(unit-standards): add styling for unit standards

---

src/services/api/webforms/ABP6/v202401.ts

We fixed minor stlying issues from HCD feedback
https://qmacbis.atlassian.net/browse/OY2-28877

fix(hcd-abp6): fix issues from hcd feedback

---

src/services/api/webforms/ABP4/v202401.ts
src/services/api/webforms/ABP6/v202401.ts
src/services/api/webforms/ABP9/v202401.ts
src/services/data/handlers/sinkMain.ts
src/services/email/ses-email-templates/index.js
src/services/ui/src/components/Inputs/input.tsx

Simple Email Template Fix for Temporary Extensions
See the following Screenshot from testing in Dev: 
](url)
Testing in DEV using cloud front URI: 
https://d1i16gckupibjp.cloudfront.net/dashboard?tab=waivers&os=N4IgZglgNgLgpgJwM4gFwG0C6AaES4CGCAxgBZogi4wEBGFA7gRAG6Iq4AOBA5hAHYEYEAPb80ofgFcAtrURoADLiQQAXnDQAmAKwBfFSIQwJ4CHCgATCkim0ZEJKrEARIZtxHLC1CG9JiED09IA

Oy2 28897 v2

---

lib/libs/webforms/ABP7/v202401.ts

This PR adds a new dependency identified by HCD (see Slack conversation [here](https://fearless.slack.com/archives/C05TUDFN02J/p1722013984479079)) and fixes the capitalization of a word.
https://qmacbis.atlassian.net/browse/OY2-28878
I added `dependency` objects to each of the components that should only appear when the select menu is set to "Yes".

feat(ABP 7): HCD feedback items

---

test/users/app-users.json

The purpose of this PR is to add a new user that gets seeded for the purposes of testing the dashboard with no data in it.

feat(add-new-test-user): Add a new user for Testing

---

lib/libs/webforms/ABP1/v202402.ts
lib/libs/webforms/ABP2A/v202401.ts
react-app/src/components/Inputs/input.tsx
react-app/src/components/RHF/FieldArray.tsx

This PR addresses UI fixes outlined by HCD. (For reference, see [the Figma here](https://www.figma.com/design/SqatGKZlgbftdOM7zMqq08/MMDL-Alternative-Benefit-Plan-(ABP)-Forms-(all)?node-id=0-1&node-type=CANVAS&t=ZwSDh93VbTaKXEvy-0).
https://qmacbis.atlassian.net/browse/OY2-30060
* Align radio buttons vertically with label text
* Fix spacing for Input components with icons
* Add missing horizontal dividers
* Update copy text to reflect Figma wireframe

fix(webform): HCD feedback for ABP 1 and 2a

---

react-app/src/features/profile/index.tsx
react-app/src/features/profile/profile.test.tsx

Some tests validating correct `Profile` behavior
https://qmacbis.atlassian.net/browse/OY2-29683

test(ui): write tests for `Profile`

---

react-app/src/utils/formOrigin.ts

This will fix the dashboard navigation issue

fix(new-sub-navigation): Fix the dashboard not working when navigating from a new form submission

---

lib/libs/webforms/ABP2C/v202401.ts
react-app/src/components/RHF/FormGroup.tsx
react-app/src/components/RHF/Section.tsx
react-app/src/components/RHF/Slot.tsx
react-app/src/components/RHF/tests/Slot.test.tsx

Adjust gap spacing to match HCD standards. Change text box size, fix label spacing.
[ticket 1](https://qmacbis.atlassian.net/browse/OY2-30286?atlOrigin=eyJpIjoiYjYzNTM5ZGNhY2U4NDNlMGFjMDgyM2Y5NDY4NzI3NTAiLCJwIjoiaiJ9)
[ticket 2](https://qmacbis.atlassian.net/browse/OY2-30460?atlOrigin=eyJpIjoiN2VlNGQxMjkwZjg1NDQ1MWJkZjE3MTM1ODI5M2NlOGUiLCJwIjoiaiJ9)

fix: abp2c spacing and hcd changes

---

test/e2e/tests/home/appendixKamendment.spec.ts
test/e2e/tests/home/capitatedamendwaiver.spec.ts
test/e2e/tests/home/capitatedinitialwaiver.spec.ts
test/e2e/tests/home/capitatedrenewalwaiver.spec.ts
test/e2e/tests/home/chipspa.spec.ts
test/e2e/tests/home/contractingamendwaiver.spec.ts
test/e2e/tests/home/contractinginitialwaiver.spec.ts
test/e2e/tests/home/contractingrenewalwaiver.spec.ts
test/e2e/tests/home/exportfeature.spec.ts
test/e2e/tests/home/filters.spec.ts
test/e2e/tests/home/medicaidspa.spec.ts
test/e2e/tests/home/packagedetailspage.spec.ts
test/e2e/tests/home/tempextension.spec.ts
test/e2e/tests/home/userprofile.spec.ts

Added files for Initial submissions.  This is a place holder and code will added soon. 
Got rid of some extra stuff.

feat(add-e2e-tests): Initial Submissions

---

react-app/src/features/forms/waiver/temporary-extension/index.tsx
react-app/src/features/forms/waiver/temporary-extension/temporary-extension.test.tsx

fix(ui): `val` fixes for Temporary Extension

---

.github/PULL_REQUEST_TEMPLATE.md

I'm tired of the old PR template, so I've decided to renew it

feat(workspace): update PR template

---

react-app/src/components/ActionForm/ActionFormAttachments.tsx
react-app/src/components/ActionForm/actionForm.components.tsx
react-app/src/components/ActionForm/index.tsx
react-app/src/components/Cards/SectionCard.tsx
react-app/src/components/Form/content/ContentWrappers.tsx
test/e2e/tests/sub-doc/medicaidSPADetail.spec.ts
test/e2e/tests/sub-doc/medicaidSubDocDetail.spec.ts

Implement a general UI framework and increase coverage of Sub Doc e2e
none
Builds e2e structure for supporting forms
Still needs a deeper dive into cards and how test-dataids can cascade down from a parent element to a child element.

feat(add general UI): add general UI validation for Sub-doc

---

.github/PULL_REQUEST_TEMPLATE.md

feat: add a comment about the PR title

---

lib/packages/shared-utils/package-actions/rules.ts

https://jiraent.cms.gov/browse/OY2-31650

fix(update-rules-for-chip): Update Chip Rules to show Enable Rai Withdraw Response

---

.github/workflows/deploy.yml
bin/cli/src/commands/e2e.ts
test/e2e/playwright.config.ts
test/e2e/tests/a11y/index.spec.ts

no JIRA item
Should improve deployment process, removing duplicate playwright install
and limit to only chromium install
change deploy.yml
cli command e2e.ts

feat: update e2e deploy step

---

lib/libs/email/content/upload-subsequent-documents/emailTemplates/Waiver1915BCMS.tsx
lib/libs/email/content/upload-subsequent-documents/emailTemplates/Waiver1915BState.tsx
lib/libs/email/content/upload-subsequent-documents/emailTemplates/index.tsx
lib/libs/email/mock-data/upload-subsequent-documents.ts
lib/libs/email/preview/Upload Subsequent Documents/CMS/Waiver1915b.tsx
lib/libs/email/preview/Upload Subsequent Documents/State/Waiver1915b.tsx

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=6700&projectKey=OY2&view=detail&selectedIssue=OY2-30723&quickFilter=40508#)
Adding  email notficiations for state and cms for upload subsequent documents
None

feat(Upload Waiver)  OY2-30723 1915(b) waivers

---

react-app/src/components/Footer/index.tsx
react-app/src/components/Layout/index.tsx
react-app/src/components/UsaBanner/index.tsx
react-app/src/features/faq/content/abpGuides.ts
react-app/src/features/faq/content/abpTemplate.tsx
react-app/src/features/faq/content/chpGuides.tsx
react-app/src/features/faq/content/chpTemplates.tsx
react-app/src/features/faq/content/mpcGuides.ts
react-app/src/features/faq/content/mpcTemplates.ts
react-app/src/features/faq/content/oneMACFAQContent.tsx
react-app/src/features/welcome/index.tsx

[OY2-31418](https://jiraent.cms.gov/browse/OY2-31418)
- update a bunch of imports to remove the annoying development console logs about improper usage of asset imports
- fix the actual bug by updating the anchor text to `c`

fix(ui): FAQ dropdown for Temporary Extensions

---

lib/libs/email/preview/Initial Submissions/CMS/__snapshots__/InitialSubmissionCMS.test.tsx.snap
lib/libs/email/preview/Initial Submissions/State/__snapshots__/InitialSubmissionState.test.tsx.snap
lib/libs/email/preview/Respond to Rai/State/__snapshots__/ResToRaiState.test.tsx.snap

Tests are failing because some snapshots need to be updated.

chore(tests): Update vitest snapshots

---

lib/libs/email/mock-data/attachments.ts
lib/libs/email/mock-data/new-submission.ts
lib/libs/email/mock-data/respond-to-rai.ts
lib/libs/email/mock-data/temp-extension.ts
lib/libs/email/mock-data/upload-subsequent-documents.ts
lib/libs/email/mock-data/withdraw-rai.ts
lib/libs/email/preview/Initial Submissions/CMS/__snapshots__/InitialSubmissionCMS.test.tsx.snap
lib/libs/email/preview/Initial Submissions/State/__snapshots__/InitialSubmissionState.test.tsx.snap
lib/libs/email/preview/Respond to Rai/State/__snapshots__/ResToRaiState.test.tsx.snap

Fixing issues with the data for unit test.  There was an issue where the templates would get loaded before the mocking of the Date.now() function in javascript causing the new date to not work on certain test.
This only affects the test and does not need verification other than test passing.

feat(test) Updating data for snapshots

---

lib/lambda/processEmails.test.ts
lib/libs/email/content/new-submission/index.tsx
lib/libs/email/getAllStateUsers.ts
mocks/handlers/aws/email.ts

feat(test) fix email test

---

lib/lambda/getForm.test.ts

feat(test) additional coverage for get from

---

lib/libs/email/content/newSubmission/index.tsx

https://jiraent.cms.gov/browse/OY2-31431
https://jiraent.cms.gov/browse/OY2-31432
Iterating through Padma's feedback

fix(email-verbiage): Additional QE feedback for initial email templates

---

react-app/src/components/TimeoutModal/index.tsx

[OY2-32113](https://jiraent.cms.gov/browse/OY2-32113)
- add class name for screen readers

fix(ui): hide timeout modal description

---

lib/lambda/getPackageActions.test.ts
lib/libs/api/package/appk.test.ts
lib/libs/email/vitest.setup.ts
lib/packages/shared-utils/package-actions/getAvailableActions.test.ts
lib/packages/shared-utils/package-actions/getAvailableActions.ts
lib/packages/shared-utils/package-actions/rules.test.ts
lib/packages/shared-utils/package-actions/rules.ts
lib/packages/shared-utils/package-check.test.ts
mocks/data/items.ts
mocks/data/users/index.ts
mocks/handlers/api/cpocs.ts
mocks/handlers/api/index.ts
mocks/handlers/api/items.ts
mocks/handlers/api/packageActions.ts
mocks/handlers/api/submissions.ts
mocks/index.d.ts
react-app/src/api/getAttachmentUrl.test.ts
react-app/src/api/itemExists.test.ts
react-app/src/api/itemExists.ts
react-app/src/api/useGetCPOCs.test.ts
react-app/src/api/useGetCPOCs.ts
react-app/src/api/useGetPackageActions.test.ts
react-app/src/api/useGetPackageActions.ts

Additional tests for package actions.

feat(test): adding tests for getting package actions

---

lib/lambda/getAllForms.test.ts
lib/lambda/getAllForms.ts
lib/lambda/getForm.test.ts
lib/lambda/getForm.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-32445)
A slight refactor of the getform lambda and a unit test with it

feat(test) new test for get form

---

vitest.config.ts

Removing test files from our coverage number as well as scroll to top coponent

feat(test)Test cov cleanup

---

lib/lambda/getAttachmentUrl.test.ts
lib/lambda/getAttachmentUrl.ts
mocks/consts.ts
mocks/handlers/aws/credentials.ts

[](https://jiraent.cms.gov/browse/OY2-32776)
Just adding more coverage to the getattachmenturls lambda

feat(test) attachment url

---

react-app/src/features/selection-flow/options.tsx

[Ticket to close](https://jiraent.cms.gov/browse/OY2-31500)
* Updates text on the "New Submission" Medicaid SPA card choice

feat(ui): update new submission Medicaid SPA type card choice language

---

lib/libs/email/content/respondToRai/emailTemplates/WaiverCMS.tsx
lib/libs/email/content/respondToRai/emailTemplates/WaiverState.tsx
lib/libs/email/content/respondToRai/index.tsx
lib/libs/email/preview/RespondToRai/CMS/__snapshots__/ResToRaiCMS.test.tsx.snap
lib/libs/email/preview/RespondToRai/State/__snapshots__/ResToRaiState.test.tsx.snap
lib/packages/shared-utils/action-type.ts

[OY2-32666](https://jiraent.cms.gov/browse/OY2-32666)
- update subject to include `actionType` instead of `authority`
- remove cc's for state emails

fix(email): add `actionType` to subject; remove cc's

---

.github/workflows/deploy.yml

Removing running unit test as part of the deploy process.  Wil still run the test for coverage.  This PR is part 1 to remove it from the required steps.  Github actions was requiring it  if it was removed at the same time from the flow and required for reasons.

feat(update) remove test from deploy

---

lib/libs/email/content/respondToRai/emailTemplates/ChipSpaCMS.tsx
lib/libs/email/content/respondToRai/emailTemplates/ChipSpaState.tsx
lib/libs/email/preview/RespondToRai/CMS/__snapshots__/ResToRaiCMS.test.tsx.snap
lib/libs/email/preview/RespondToRai/State/__snapshots__/ResToRaiState.test.tsx.snap

[Ticket to close](https://jiraent.cms.gov/browse/OY2-32665)
Quick textual updates and snapshot fixes. Changes regarding multiple CC are secret based.

fix: text fixes for chip rai response emails

---

lib/lambda/getPackageActions.test.ts
lib/lambda/search.test.ts
lib/packages/shared-types/actions.ts
lib/packages/shared-utils/package-actions/getAvailableActions.test.ts
lib/packages/shared-utils/package-actions/getAvailableActions.ts
mocks/data/items.ts

[OY2-32030](https://jiraent.cms.gov/browse/OY2-32030)
The order of package actions wasn't how it was wanted to be.  I updated the logic to display the order of the actions to be based on how the enum is ordered as opposed to just how it gets returned from he service.  This will allow us to have a custom order in how we want it to be.
Updated the logic of getAvailableActions to use the enums natural ordering.
Updated the unit test for getAvailableActions since the changes caused existing test to fail(expected)

feat(ui)Update action order

---

lib/lambda/processEmails.ts
lib/libs/email/content/newSubmission/emailTemplates/Waiver1915bCMS.tsx
lib/libs/email/content/newSubmission/emailTemplates/Waiver1915bState.tsx
lib/libs/email/content/respondToRai/emailTemplates/WaiverCMS.tsx
lib/libs/email/content/respondToRai/emailTemplates/WaiverState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/AppKCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/AppKState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/ChipSpaCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/ChipSpaState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/MedSpaState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/Waiver1915BCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/Waiver1915BState.tsx
lib/libs/email/content/uploadSubsequentDocuments/index.tsx
lib/libs/email/preview/InitialSubmissions/CMS/AppK.tsx
lib/libs/email/preview/InitialSubmissions/CMS/Medicaid_SPA.tsx
lib/libs/email/preview/InitialSubmissions/CMS/Waiver1915bContracting/Initial.tsx
lib/libs/email/preview/InitialSubmissions/State/Waiver1915bCapitated/Initial.tsx
lib/libs/email/preview/InitialSubmissions/State/Waiver1915bContracting/Initial.tsx
lib/libs/email/preview/RespondToRai/CMS/Waiver.tsx
lib/libs/email/preview/RespondToRai/State/Waiver.tsx
lib/libs/email/preview/UploadSubsequentDocuments/CMS/Waiver1915b.tsx
lib/libs/email/preview/UploadSubsequentDocuments/CMS/__snapshots__/UpSubDocCMS.test.tsx.snap
lib/libs/email/preview/UploadSubsequentDocuments/State/__snapshots__/UpSubDocState.test.tsx.snap

- I've decided to move the formatActionType into the email variable that's passed to the templates so we don't keep adding ${formatActionType(variables.id)} everywhere. I think this change simplifies the logic and doesn't confuse others down the line
- update the upload-subsequent-emails templates per testing feedback

chore(ui): Subsequent Upload Documents feedback

---

lib/packages/shared-utils/action-type.ts
react-app/src/features/dashboard/Lists/waivers/consts.tsx
react-app/src/features/dashboard/Lists/waivers/index.test.tsx
react-app/src/features/package/package-details/hooks.tsx
react-app/src/utils/index.ts
react-app/src/utils/labels.ts

While this PR serves as a fix for an action type update in emails, it also introduces some more logic consolidation when it comes to language

fix(emails): update `formatActionType` to display `Renewal`

---

lib/libs/email/content/uploadSubsequentDocuments/index.tsx

- update subjects that I mixed up

fix(emails): update subjects for Medicaid and 1915(c)

---

react-app/src/features/dashboard/Lists/spas/index.tsx
react-app/src/features/dashboard/Lists/waivers/index.tsx

https://jiraent.cms.gov/browse/OY2-33394
- I just undid what @tiffanyvu  did here: https://github.com/Enterprise-CMCS/macpro-mako/pull/1188 because it caused an unintentional bug 
- that ticket will need to be reopened
deleted: context.isLoading in the loading condition, because `isLoading` is also true when searching & filtering not just on tab changes

fix(ui): Upgrade Dashboard Search Bar Broken

---

react-app/src/features/package/__snapshots__/index.test.tsx.snap
react-app/src/features/package/package-details/__snapshots__/package-details.test.tsx.snap
react-app/src/features/package/package-details/details.tsx

[OY2-33471](https://jiraent.cms.gov/browse/OY2-33471)

chore(ui): update Package Details capitalization

---

.github/workflows/auto-create-pr-production.yml
.github/workflows/auto-create-pr-val.yml
.github/workflows/destroy.yml
.github/workflows/lint.yml
.github/workflows/pre-commit.yml
.github/workflows/security-group-cleanup.yml

https://github.com/actions/runner-images/issues/11101
Need to update runner images.

fix: update ubuntu runners

---

react-app/src/features/selection-flow/plan-types.tsx

[Ticket to close](https://jiraent.cms.gov/browse/OY2-33525)
Remove the " . " from the "Select a Submission Type." card choice

fix(text):removing period

---

react-app/src/features/selection-flow/plan-types.tsx

[Ticket to close](https://jiraent.cms.gov/browse/OY2-33525)
Based on feedback from CMS during a demo on 3.4.25, the " . " should be removed from the Submission Type card choice in OM Upgrade. 
Although this was confirmed to align with how the card choice appears in Legacy, CMS agreed that it should not be displayed.

chore(ui): removing period from all submission types

---

bin/cli/src/commands/logs.ts
eslint.config.mjs
lib/lambda/getAttachmentUrl.ts
lib/lambda/sinkMainProcessors.ts
lib/libs/api/auth/user.ts
lib/libs/api/statusMemo.ts
lib/libs/opensearch-lib.ts
lib/local-constructs/clamav-scanning/src/handlers/defs.ts
lib/local-constructs/clamav-scanning/src/lib/clamav.ts
lib/local-constructs/clamav-scanning/src/lib/s3.ts
mocks/handlers/aws/credentials.ts
mocks/handlers/aws/idm.ts
react-app/src/api/useGetTypes.ts
react-app/src/components/RHF/dependencyWrapper.tsx
react-app/src/components/RHF/utils/additionalRules.ts
react-app/src/features/faq/content/expandCollapseBtn.tsx
react-app/src/features/webforms/WebFormBody.tsx

Adding a sensible convention to standardize early returns

chore(workspace): add new eslint rule and fix new errors

---

lib/libs/email/mock-data/attachments.ts
lib/libs/email/mock-data/upload-subsequent-documents.ts
lib/libs/email/mock-data/withdraw-rai.ts
lib/libs/email/preview/InitialSubmissions/CMS/SnapshotTest/__snapshots__/CHIP_SPA.test.tsx.snap
lib/libs/email/preview/InitialSubmissions/CMS/SnapshotTest/__snapshots__/Medicaid_SPA.test.tsx.snap
lib/libs/email/preview/InitialSubmissions/CMS/__snapshots__/InitialSubmissionCMS.test.tsx.snap
lib/libs/email/preview/UploadSubsequentDocuments/CMS/__snapshots__/UpSubDocCMS.test.tsx.snap
lib/libs/email/preview/UploadSubsequentDocuments/State/__snapshots__/UpSubDocState.test.tsx.snap
lib/packages/shared-types/attachments.ts
lib/packages/shared-types/events/new-medicaid-submission.ts
lib/packages/shared-utils/testData.ts
mocks/data/submit/attachments.ts
react-app/src/components/Form/old-content.tsx
react-app/src/features/faq/content/oneMACFAQContent.tsx
react-app/src/features/forms/new-submission/Medicaid.tsx
test/e2e/package-actions/sub-doc/medicaid-sub-doc-detail.spec.ts
test/e2e/tests/sub-doc/medicaidSubDocDetail.spec.ts

[OY2-33680](https://jiraent.cms.gov/browse/OY2-33680)
- relevant text changes
- remove dead code with old text

chore(ui): change CMS Form 179 to CMS-179 Form

---

lib/libs/webforms/index.ts

skipci fix lint

---

react-app/src/components/Opensearch/main/Filtering/Export/Export.test.tsx
react-app/src/components/Opensearch/main/Filtering/Export/index.tsx
react-app/src/components/Opensearch/main/Filtering/Filtering.test.tsx
react-app/src/components/Opensearch/main/Filtering/index.tsx
react-app/src/components/Opensearch/main/index.tsx

[Ticket to close](https://jiraent.cms.gov/browse/OY2-27173)
* Adds a confirmation dialog when attempting to export more than 10k records

feat(ui): Show a modal when attempting to export more than 10,000 records

---

.github/workflows/pre-commit.yml
lib/lambda/search.ts
react-app/src/api/useSearch.ts

[
[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-33785)
All legacy is appearing in search when it should only be seatool.  Updating the OS query to only make it NOSO.
Had to update the github action for precommit.  It was causing issues due to incompatible python issues.  Set a fixed version of it and it seemed to resolve.
No unit test despite the ticket.  Our OS test use a lot of fake stuff so i "acts" like OS but it behaves nothing like it in actuality.  
Search for MD-2333.R00.00 in DEV since this is NOSO

feat(bug) - remove seatool minus noso from search

---

react-app/src/features/welcome/utils.ts
react-app/src/features/welcome/utils.tsx
react-app/src/router.tsx

https://jiraent.cms.gov/browse/OY2-33904
- momentarily turned off LD flag to test this
- should be able to navigate to the FAQ page without being logged in
- updated the utils in welcome 
- also fixed an error I found in router

fix(ui): FAQ shouldn't be hidden behind loggin when LD flag off 

---

lib/packages/shared-utils/feature-flags.ts
react-app/src/components/Layout/index.tsx
react-app/src/features/dashboard/index.tsx
react-app/src/features/login/index.tsx
react-app/src/features/welcome/utils.ts
react-app/src/main.tsx
react-app/src/router.test.tsx
react-app/src/router.tsx

Should've been hidden behind feature flag. Might mess up UAT otherwise.

fix: hide login behind feature flag

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/amendment-waiver.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/app-k.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/initial-waiver.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/renewal-waiver.ts

[OY2-33753](https://jiraent.cms.gov/browse/OY2-33753)
- update the borken `actionType`

fix(lambda): update legacy action types

---

lib/packages/shared-types/events/app-k.ts
lib/packages/shared-types/events/base-schema.ts
lib/packages/shared-types/events/capitated-amendment.ts
lib/packages/shared-types/events/capitated-initial.ts
lib/packages/shared-types/events/capitated-renewal.ts
lib/packages/shared-types/events/contracting-amendment.ts
lib/packages/shared-types/events/contracting-initial.ts
lib/packages/shared-types/events/contracting-renewal.ts
lib/packages/shared-types/events/new-chip-submission.ts
lib/packages/shared-types/events/new-medicaid-submission.ts
lib/packages/shared-types/events/respond-to-rai.ts
lib/packages/shared-types/events/temporary-extension.ts
lib/packages/shared-types/events/toggle-withdraw-rai.ts
lib/packages/shared-types/events/upload-subsequent-documents.ts
lib/packages/shared-types/events/withdraw-package.ts
lib/packages/shared-types/events/withdraw-rai.ts
react-app/src/components/ActionForm/index.tsx

Small PR.  This is just some tech-debt clean up I came across while working on another ticket.  We share the same schema across the different files, just repeated over all the different files.  This is just a refactor.

tech-debt(cleanup)  Combining shared-types with shared schemas

---

react-app/src/api/useSearch.test.ts
react-app/src/api/useSearch.ts
react-app/src/components/Opensearch/main/Filtering/Export/index.tsx

[OY2-33770](https://jiraent.cms.gov/browse/OY2-33770)

fix(ui): add sort arg to export function

---

react-app/src/features/faq/content/oneMACFAQContent.tsx
test/e2e/faq/faq.spec.ts

[OY2-32361](https://jiraent.cms.gov/browse/OY2-32361)
Business provided updated text for the first FAQ item, so replacing question text and adding additional text to answer.
Updating FAQ Content to accomodate updated language for crosswalk question.

feat(ui): Add text for FAQ question

---

lib/packages/shared-types/attachments.ts
lib/packages/shared-types/opensearch/changelog/transforms/new-medicaid-submission.ts
lib/packages/shared-types/opensearch/changelog/transforms/upload-subsequent-documents.ts

[OY2-33725](https://jiraent.cms.gov/browse/OY2-33725)
- a simple conditional to check whether the attachment label is the outdated one. Since this is a temporary but long term fix, is there any way to abstract this so it's not hideous?

chore(lambda): add conditional for attachment `title`

---

react-app/src/components/Layout/index.tsx
react-app/src/components/SupportPage/contactHelpDesk.tsx
react-app/src/components/SupportPage/expandCollapseBtn.test.tsx
react-app/src/components/SupportPage/index.ts
react-app/src/components/SupportPage/search.test.tsx
react-app/src/components/SupportPage/search.tsx
react-app/src/components/SupportPage/statusLabel.test.tsx
react-app/src/components/SupportPage/statusLabel.tsx
react-app/src/features/support/SupportMockContent.tsx
react-app/src/features/support/SupportPage.test.tsx
react-app/src/features/support/SupportPage.tsx

- https://jiraent.cms.gov/browse/OY2-33888
- https://jiraent.cms.gov/browse/OY2-32874
- created just the design/UI of the search bar component 
- moved the logic to a different branch to work on next/future sprint
- created new component rather than using the search on the dashboard bc functionality & design are different open to feedback on that
- created the component for the "new" | "updated" tags 
- added office ours to the help desk (based on feedback from HCD)
- added blue box on latest clicked on

feat(ui): Search Bar UI & Status tags

---

bin/cli/src/lib/write-ui-env-file.ts

feat(bug) Google analytics fix

---

lib/lambda/sinkMainProcessors.test.ts
lib/lambda/sinkMainProcessors.ts
lib/packages/shared-types/opensearch/main/transforms/seatool.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-33958)
Status is updated to In Review before save in Seatool.  Seatool automatically saves in its database at a certain point to most likely hold the waiver number in its database without a subject or description. 
Updated the transform  function for Seatool to require a summary and description in order to save if the status is "Is Pending" in seatool.
Coverage went down a little bit because I am removing a lot of unnecessary logs.

feat(bug) early status update

---

react-app/src/components/Layout/index.tsx
react-app/src/components/TimeoutModal/index.tsx

https://jiraent.cms.gov/browse/OY2-33959
Updated enhances banner with new text and buttons. Also added logic to persist notifications if exited even when the user signs out

fix(persist-notifications): Add logic to persist banner notifications even on sign out

---

react-app/src/components/Layout/index.tsx

[OY2-33921](https://jiraent.cms.gov/browse/OY2-33921)
- move items into a valid list
- remove buttons and rely on the `onSelect` prop

fix(ui): profile dropdown compliance

---

test/e2e/dashboard/dashboard.spec.ts
test/e2e/home/home.spec.ts
test/e2e/home/no-auth.spec.ts
test/e2e/home/user-profile.spec.ts
test/fixtures/home.page.text.ts
test/lib/auth.setup.ts
test/non-func/a11y/index.spec.ts
test/pages/home.page.ts
test/pages/login.page.ts
test/playwright.config.ts

feat: home page smoke tests

---

react-app/src/features/welcome/cms.test.tsx
react-app/src/features/welcome/cms.tsx

https://jiraent.cms.gov/browse/OY2-34211
Need to -
Add "Tool" after "State Early Alert"
Fix spelling of "Laserfiche" (no s, no capitalization of the "f")

fix(ui): fixed language on cms home view

---

test/e2e/home/user-profile.spec.ts
test/lib/auth.secrets.ts
test/lib/auth.setup.ts
test/lib/global.setup.ts
test/lib/global.teardown.ts
test/pages/login.page.ts
test/playwright.config.ts

feat: refactor auth setup and teardown

---

react-app/src/components/Opensearch/main/Filtering/Export/Export.test.tsx
react-app/src/components/Opensearch/main/Filtering/Export/index.tsx
react-app/src/components/Opensearch/main/Filtering/Filtering.test.tsx
react-app/src/components/Opensearch/main/Settings/Visibility.test.tsx
react-app/src/components/Opensearch/main/Settings/Visibility.tsx
react-app/src/components/Opensearch/main/Table/index.tsx
react-app/src/components/Opensearch/main/index.test.tsx
react-app/src/features/dashboard/Lists/renderCells/index.tsx
react-app/src/features/dashboard/Lists/spas/index.test.tsx
react-app/src/features/dashboard/Lists/waivers/index.test.tsx
react-app/src/features/dashboard/index.test.tsx

[OY2-33919](https://jiraent.cms.gov/browse/OY2-33919)
Tests needed to be updated due to updated controls and behavior
https://github.com/user-attachments/assets/31e0314e-29c7-4c7f-b99a-a8a08cb91900

feat(ui): Columns Button Compliance Enhancements

---

react-app/src/features/dashboard/Lists/renderCells/index.test.tsx
react-app/src/features/dashboard/Lists/renderCells/index.tsx

[OY2-33920](https://jiraent.cms.gov/browse/OY2-33920)
https://github.com/user-attachments/assets/24841c1f-5640-422f-83d3-1c9af8504677

feat(ui): Row-level Menu Compliance Enhancements 

---

react-app/src/components/Banner/MMDLSpaBanner.tsx
react-app/src/components/Inputs/button.tsx
react-app/src/components/Opensearch/main/Filtering/Drawer/index.test.tsx
react-app/src/components/Opensearch/main/Filtering/Drawer/index.tsx
react-app/src/components/Opensearch/main/Filtering/Filtering.test.tsx
react-app/src/components/Tabs/index.tsx
react-app/src/features/dashboard/Lists/renderCells/index.tsx
react-app/src/features/dashboard/index.test.tsx
react-app/src/features/dashboard/index.tsx
react-app/src/features/faq/__snapshots__/Faq.test.tsx.snap
react-app/src/features/forms/post-submission/toggle-withdraw-rai/__snapshots__/index.test.tsx.snap
react-app/src/features/forms/post-submission/withdraw-package/__snapshots__/indext.test.tsx.snap
react-app/src/features/package/index.tsx
react-app/src/features/package/package-activity/index.tsx

[OY2-34336](https://jiraent.cms.gov/browse/OY2-34336),
[OY2-34337](https://jiraent.cms.gov/browse/OY2-34337),
[OY2-34338](https://jiraent.cms.gov/browse/OY2-34338),
[OY2-34339](https://jiraent.cms.gov/browse/OY2-34339),
[OY2-34340](https://jiraent.cms.gov/browse/OY2-34340),
[OY-34425](https://jiraent.cms.gov/browse/OY2-34425)
- I changed the default button styles. I checked and didn't find `variant="default"` being used anywhere else other than the `Submit` button in the forms
- the default `Tabs` component was updated (copied styles from the `ToggleGroup`) as it was only used in the `Dashboard`
Please peruse the [Doc](https://docs.google.com/document/d/1ifWMFjuNXmjwMgfntsoNnSOer5_HHfzbjcCr90cu9AY)

feat(ui): Release UI Improvements

---

react-app/src/components/Inputs/button.tsx
react-app/src/components/Opensearch/main/Filtering/Drawer/index.tsx
react-app/src/components/Tabs/index.tsx
react-app/src/components/ToggleGroup/ToggleGroupItem.tsx
react-app/src/features/faq/__snapshots__/Faq.test.tsx.snap
react-app/src/features/forms/post-submission/toggle-withdraw-rai/__snapshots__/index.test.tsx.snap
react-app/src/features/forms/post-submission/withdraw-package/__snapshots__/indext.test.tsx.snap
react-app/src/features/package/__snapshots__/index.test.tsx.snap
react-app/src/features/package/admin-changes/__snapshots__/admin-features.test.tsx.snap
react-app/src/features/package/admin-changes/index.tsx

https://jiraent.cms.gov/browse/OY2-34340
https://jiraent.cms.gov/browse/OY2-34338
https://jiraent.cms.gov/browse/OY2-34336

fix(ui): Design Follow-ups

---

lib/packages/shared-types/opensearch/changelog/index.ts
react-app/src/features/package/package-activity/index.tsx

Missing legacy fix

---

react-app/src/components/Opensearch/main/Filtering/index.tsx
react-app/src/components/SearchForm/index.tsx
react-app/src/features/welcome/cms.test.tsx
react-app/src/features/welcome/cms.tsx
react-app/src/features/welcome/packageSearch.tsx
react-app/src/features/welcome/state.tsx

[OY2-33589](https://jiraent.cms.gov/browse/OY2-33589)
Add search functionality for the cms and state home views.

feat: add search function to new home pages

---

react-app/src/features/profile/index.tsx
test/README.md
test/e2e/dashboard/dashboard.spec.ts
test/e2e/home/user-profile.spec.ts
test/lib/auth.secrets.ts
test/lib/auth.setup.ts
test/lib/ci.setup.ts
test/lib/eua.setup.ts
test/lib/global.setup.ts
test/lib/global.teardown.ts
test/lib/local.setup.ts
test/lib/mfa.setup.ts
test/package.json
test/pages/login.page.ts
test/playwright.config.ts

feat: use MFA on prod url and increase coverage

---

lib/lambda/user-management/updateUserRoles.ts

Add jsdoc for updateUserRoles lambda function

chore(lambda): add jsdoc for updateuserroles lambda

---

lib/packages/shared-utils/feature-flags.ts
react-app/src/components/Layout/index.test.tsx
react-app/src/components/Layout/index.tsx

This should have had its own flag from the beginning.

fix: webform tab needs its own flag

---

lib/packages/shared-types/events/new-chip-details-submission.ts
react-app/src/components/BreadCrumb/create-breadcrumbs.ts
react-app/src/features/forms/new-submission/ChipDetails.tsx
react-app/src/features/selection-flow/options.tsx
react-app/src/router.tsx
test/fixtures/routes.ts

removed MMDL abp card from medspa options

fix: removed mmdl abp card

---

react-app/src/components/Opensearch/main/Filtering/Drawer/Filterable/Select.tsx

No ticket for this atm
- I had to edit the way we created the multi select component so that the 'label' is actually a label instead of the value, whereas before I was overwriting the value with the label

fix(ui): state signup page sending the label now as the data value

---

react-app/src/features/package/__snapshots__/index.test.tsx.snap
react-app/src/features/package/package-details/__snapshots__/package-details.test.tsx.snap
react-app/src/features/package/package-details/details.tsx

[OY2-33601](https://jiraent.cms.gov/browse/OY2-33601)

feat(ui): Group SEATOOL dates together

---

test/e2e/smoke/cms/dashboard.spec.ts
test/e2e/smoke/cms/profile.spec.ts
test/e2e/smoke/state/appk.spec.ts
test/e2e/smoke/state/chip.spec.ts
test/e2e/smoke/state/dashboard.spec.ts
test/e2e/smoke/state/medicaid.spec.ts
test/e2e/smoke/state/profile.spec.ts
test/e2e/smoke/state/waiver-cap.spec.ts
test/e2e/smoke/state/waiver-ffs.spec.ts
test/fixtures/metadata/TestMetadata.ts
test/fixtures/metadata/dashboard.meta.json
test/lib/auth.setup.ts
test/lib/baseURLs.ts
test/lib/eua.setup.ts
test/lib/local.setup.ts
test/lib/metadata.handler.ts
test/lib/mfa.setup.ts
test/lib/smoke.setup.ts
test/pages/dashboard.page.ts
test/playwright.config.ts

feat: add smoke tests

---

react-app/src/components/ActionForm/index.tsx
react-app/src/components/Inputs/upload.tsx

[OY2-35021](https://jiraent.cms.gov/browse/OY2-35021)
App is disregarding the pop up action and package/sub docs or any other action is being submitted with the deleted files.
- added a type to the delete file button

bug(ui): Action form submit issue

---

react-app/src/components/Inputs/upload.test.tsx
react-app/src/components/Inputs/upload.tsx

Update language per requirement
[Ticket to close](https://jiraent.cms.gov/browse/OY2-33876)
Change "Delete" to "Remove"

fix: update modal language

---

mocks/data/roles.ts
mocks/handlers/api/user.ts
mocks/handlers/aws/secretsManager.ts
mocks/handlers/search.utils.ts
react-app/src/components/RHF/tests/FieldArray.test.tsx
react-app/src/components/RHF/tests/RHFTextDisplay.test.tsx
react-app/src/components/RHF/tests/Section.test.tsx
react-app/src/features/package/package-actions/index.tsx
react-app/src/features/package/package-status/index.tsx

Cleaning up some things in the code that Playwright does not like.
- updated all imports that end in ".." to "../index"

chore(ui): updating imports to explicitly import index 

---

react-app/src/features/faq/content/oneMACFAQContent.tsx

[OY2-35016](https://jiraent.cms.gov/browse/OY2-35016)
The table in the "What are the OneMAC user roles?" section is no longer needed and will now point to a PDF.

chore(faq): update user roles section in FAQ

---

lib/libs/email/content/withdrawRai/index.tsx

removed cpoc & srt for mediciad changed to all state submitters (#1565)

---

lib/packages/shared-types/events/new-chip-details-submission.ts
react-app/src/features/forms/new-submission/ChipDetails.tsx
react-app/src/features/selection-flow/options.test.tsx
react-app/src/features/selection-flow/options.tsx

https://jiraent.cms.gov/browse/OY2-35015
Env - DEV
Click on CHIP Eligibility SPA to create and submit the record.
Under the Attachments section, click on the FAQ Page link.
App should open the FAQ on a different tab and should anchor to that specific section on the FAQ.
Issue #1 - App is anchoring to CHIP SPA attachments instead of CHIP Eligibility SPA. This issue happens for Initial Submission and Upload Subsequent documents actions. (ask HCD)
Note - There is no section available currently on the FAQ page for CHIP Eligibility SPA.
A.  The highlighted text "FAQ page" should not be unique on this page. It should direct to the same section of the FAQs, which details attachment types. It is currently doing that. 
Issue #2 - Move the blue underlined text to the right side as mentioned in the …

fix(ui): chip eligibility form and faq changes

---

react-app/src/features/faq/content/abpGuides.ts
react-app/src/features/faq/content/mpcGuides.ts
react-app/src/features/faq/content/mpcTemplates.ts
react-app/src/features/faq/content/oneMACFAQContent.tsx
react-app/src/features/guides/index.tsx
react-app/src/features/support/SupportMockContent.tsx
test/e2e/faq/faq.spec.ts

https://jiraent.cms.gov/browse/OY2-35167
Add requested language cleanup

fix(faq cleanup):Onemac faq update with language

---

react-app/src/components/BreadCrumb/create-breadcrumbs.ts

https://jiraent.cms.gov/browse/OY2-35226
Fix breadcrum logic for mmdl UAT release

fix(chip eligibility breadcrumb): fix redundant breadcrumb

---

react-app/src/features/package/package-activity/index.tsx

https://jiraent.cms.gov/browse/OY2-35170

fix(ui): Subsequent Document(s) Uploaded

---

react-app/src/components/Profile/WithdrawRoleModal/WithdrawRoleModal.test.tsx
react-app/src/components/Profile/WithdrawRoleModal/index.tsx
react-app/src/features/sign-up/stateSignup.test.tsx
react-app/src/features/sign-up/stateSignup.tsx

[OY2-35811](https://jiraent.cms.gov/browse/OY2-35811)

fix(ui): Update User Role Signup Language

---

react-app/src/components/Profile/Information/UserInformation.test.tsx
react-app/src/components/Profile/Information/index.tsx
react-app/src/components/Profile/RoleStatusCard/ApproverInfo.tsx
react-app/src/components/Profile/RoleStatusCard/RoleStatusCardNew.tsx
react-app/src/features/profile/me/index.tsx
react-app/src/features/profile/user/index.tsx
react-app/src/features/profile/user/userprofile.test.tsx

[OY2-33937](https://jiraent.cms.gov/browse/OY2-33937)
* User Information: Replaced generic div elements with a definition list (dl, dt, dd) to properly structure user details like name, role, and email.
* Approver List: The list of approvers is now correctly structured as an unordered list (ul, li), improving its semantic meaning.
* Role Status Cards: The role status cards are now rendered within an ordered list (ol, li), which better
represents the collection of user roles.
* Dropdown Menu: The dropdown menu in the `RoleStatusCardNew` component has been updated to improve its structure and accessibility.

fix(profile): improve accessibility and structure in UserInformation and ApproverInfo components

---

react-app/src/features/package/__snapshots__/index.test.tsx.snap
react-app/src/features/package/admin-changes/__snapshots__/admin-features.test.tsx.snap
react-app/src/features/package/admin-changes/index.tsx
react-app/src/features/package/index.tsx
react-app/src/features/package/package-actions/index.tsx
react-app/src/features/package/package-activity/index.tsx
react-app/src/features/package/package-details/__snapshots__/package-details.test.tsx.snap
react-app/src/features/package/package-details/index.tsx
react-app/src/features/package/package-status/__snapshots__/package-status.test.tsx.snap
react-app/src/features/package/package-status/index.tsx

[OY2-33938](https://jiraent.cms.gov/browse/OY2-33938)
- Adding `aria-labelledby` attributes to provide accessible names for elements.
- Using semantic HTML elements like `<nav>`, `<ol>`, `<li>`, `<dl>`, `<dt>`, and <dd> to improve the structure and meaning of the content for screen readers.
- Wrapping lists of links and package activities in `<ul>` and `<ol>` elements.
- Removing a `console.log` statement from the package-activity/index.tsx file.

fix(package): enhance accessibility by adding ARIA labels and semantic HTML elements

---

lib/local-constructs/waf/index.ts
react-app/src/components/ActionForm/index.tsx

[OY2-36100](https://jiraent.cms.gov/browse/OY2-36100)

fix(waf): add custom error response for request body size limit
