src/services/database/serverless.yml

This adds point-in-time recovery (PITR) to the `Table` and `PostsTable` resources.
Addresses the SecurityHub findings in [OY2-23722](https://qmacbis.atlassian.net/browse/OY2-23722) as well as:
https://qmacbis.atlassian.net/browse/OY2-23723
https://qmacbis.atlassian.net/browse/OY2-23724
https://qmacbis.atlassian.net/browse/OY2-23725
https://qmacbis.atlassian.net/browse/OY2-23726
Followed the same apporach used in [seatool-compare](https://github.com/Enterprise-CMCS/seatool-compare/blob/master/src/services/mmdl/serverless.yml#L34).
More info available here for the very curious:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-pointintimerecoveryspecification.html#cfn-dynamodb-table-pointintimerecoveryspecification-pointintimerecoveryenabled …

feat(dynamodb): Turns on point-in-time recovery for tables

---

src/packages/shared-types/onemac.ts
src/services/ui/src/components/Opensearch/utils.ts
src/services/ui/src/components/PackageDetails/ChipSpaPackageDetails.tsx
src/services/ui/src/components/Pagination/index.tsx
src/services/ui/src/components/SubmissionInfo/index.tsx
src/services/ui/src/index.css
src/services/ui/src/lib/index.tsx
src/services/ui/src/lib/labels.ts
src/services/ui/src/pages/dashboard/Lists/spas/consts.tsx
src/services/ui/src/pages/dashboard/Lists/waivers/consts.tsx

few things here:
- add LABELS map
- add sub type column on dahsboard and details page
- change items to Records in pagination
- hacked alignment of footer
- include the CPOC name column to the dashboard
- Waiver Number instead of Waiver ID
- origin should be oneMAC not OneMAC
- Submitted By instead of Submitter on package details

feal(subtype): Add subtype labels and qa fixes

---

src/services/ui/src/components/RHF/Document.tsx
src/services/ui/src/components/RHF/FormGroup.tsx
src/services/ui/src/components/RHF/Section.tsx
src/services/ui/src/pages/form/index.tsx

This ticket:
- adjusts the font size of the topmost header
- adjusts the spacing of child elements within checkbox lists and radio groups
- adds a border around the form with a gradient at the top
- adjusts overall spacing to better match the Figma designs.
Here is an example of the incorrect spacing with multiple layers of child elements:
and how it looks after the adjustment:
The branch can be viewed and tested here: https://d8nenw68wip9a.cloudfront.net/form

fix(webforms): Spacing, font size, and border

---

src/services/api/handlers/forms.ts
src/services/api/serverless.yml
src/services/ui/src/api/index.ts
src/services/ui/src/api/useGetForm.ts
src/services/ui/src/pages/form/index.tsx

This allows the UI to receive form data from the API
https://qmacbis.atlassian.net/browse/OY2-25508
It adds a `useGetForm` method that submits a form ID and form version and receives a JSON object for the requested form.
We wrapped the returned data in the `response` wrapper to handle CORS issues, etc.

feat(UI): Add query/hook for forms API to UI 

---

src/packages/shared-types/actions.ts
src/packages/shared-types/index.ts
src/packages/shared-types/opensearch.ts
src/services/api/handlers/getPackageActions.ts
src/services/api/handlers/item.ts
src/services/api/libs/package/getPackage.ts
src/services/api/serverless.yml
src/services/ui/src/api/index.ts
src/services/ui/src/api/useGetItem.ts
src/services/ui/src/api/useGetPackageActions.ts
src/services/ui/src/components/Cards/CardWithTopBorder.tsx
src/services/ui/src/pages/actions/EnableRaiResponseWithdraw.tsx
src/services/ui/src/pages/actions/index.tsx
src/services/ui/src/pages/detail/index.tsx
src/services/ui/src/pages/index.ts
src/services/ui/src/router.tsx
src/services/ui/src/routes.ts
src/services/ui/src/utils/actionLabelMapper.ts
src/services/ui/src/utils/index.ts

This PR handles preliminary work necessary for all package actions tickets forthcoming. It enables developers to create the conditions in which a package action is to be added to the API response for an item, and render out the option on the Details page of the UI.
Does not close any issues.
Package actions are not something that come through the sink in either data model (SEA Tool or OneMAC), so we have to infer package actions available based on the data within a package **and** a user's authorization to perform each action. There is precedent for this in OneMAC [here](https://github.com/Enterprise-CMCS/macpro-onemac/blob/develop/services/app-api/getDetail.js#L89-L97).
We've implemented a similar approach in this PR with one exception: we have a designated endpoint `getPackageActions` …

feat(package actions): Set up API to return actions; UI to read and render actions

---

src/services/auth/libs/users.json
src/services/ui/src/api/useGetUser.ts
src/services/ui/src/components/Context/userContext.tsx
src/services/ui/src/components/Layout/index.tsx
src/services/ui/src/components/UsaBanner/index.tsx
src/services/ui/src/main.tsx
src/services/ui/src/pages/dashboard/Lists/spas/consts.tsx
src/services/ui/src/pages/dashboard/Lists/spas/index.tsx
src/services/ui/src/pages/dashboard/Lists/waivers/consts.tsx
src/services/ui/src/pages/dashboard/Lists/waivers/index.tsx
src/services/ui/src/pages/dashboard/index.tsx

The purpose of this ticket was to implement a logic that allows us to control the user's view in the us based on user role
https://qmacbis.atlassian.net/browse/OY2-25702
Wrote a logic that restrict dashboard view for users without proper role and directs them to a message to go to IDM upon signing into mako and sign up. 

feat(role based view): implemented a role based view for user groups

---

src/services/ui/src/pages/form/proto.tsx

A few labels and items needed small changes to reflect the Figma design exactly. This PR makes those changes.

fix(ABP1): Ensure copy text matches Figma and PDF

---

src/services/ui/src/components/UsaBanner/index.tsx
src/services/ui/src/pages/welcome/index.tsx

Needed to update the banner failure message when users with n IDM role login to mako

go team... banner for no role case

---

src/services/ui/src/components/Cards/SectionCard.tsx
src/services/ui/src/components/Cards/index.ts
src/services/ui/src/components/ExportButton/index.tsx
src/services/ui/src/components/Opensearch/Filtering/FilterDrawer.tsx
src/services/ui/src/components/Opensearch/Filtering/index.tsx
src/services/ui/src/components/SearchForm/index.tsx
src/services/ui/src/pages/form/medicaid-form.tsx

Styling changes for the dashboard and new spa submission.
Ticket [oy2-26325](https://qmacbis.atlassian.net/browse/OY2-26325?atlOrigin=eyJpIjoiYWY4NzgwYWNmNmVjNGI4Y2E1YmMwN2ZhNDBjZTE0ZmIiLCJwIjoiaiJ9)

fix(ui updates per cms):  Dashboard and Forms styling

---

src/services/ui/src/api/submissionService.ts

This changeset fixes an issue whereby multiple uploads of the same type were not handled correctly.
None.
This was found on a dev branch while looking into a finding by Padma.  It was found regarding RAI attachments, but it can be seen on dev for new submissions as well. 
Looking into it, the submission service looked to not handle having more than one of each file type.  For example, if you attached two files for 'Other' attachments, they would be reduced to just one object within the service, with only one S3 key, and ultimately only one file would be stored in S3.  Looking at package details, you would see the files that were uploaded, but clicking each of a given type would yield the same single file repeatedly.
The approach kept the service ins/outs the same, and modified upload …

fix(multi upload):  Refactor submission service fix

---

src/services/api/layers/ABP1/v1.ts

Changes regex to disallow zero for household size based on HCD feedback.

fix: disallow zero household size

---

src/services/ui/src/pages/actions/RespondToRai.tsx

This PR wraps an action form we missed during creation with the component that checks auth for an action.
N/A
N/A
Can be tested by arriving at any action url (i.e. `/action/{packageId}/{actionType}`), for a package that is not authorized to respond to an RAI yet, and replacing the `actionType` with `respond-to-rai`

fix(package-actions): Wrap `RespondToRai` with package action checks

---

src/packages/shared-types/actions.ts
src/packages/shared-types/planType.ts
src/packages/shared-utils/index.ts
src/packages/shared-utils/package-actions/getAvailableActions.ts
src/packages/shared-utils/package-actions/rules.ts
src/packages/shared-utils/packageCheck.ts
src/services/ui/src/pages/detail/index.tsx

This PR cleans up our new package checks a bit to unify them. They're written to be easily refactored to lazy load if the object gets too heavy, or broken out into their own objects if individual services become more useful.
N/A
Taking `PlanTypeCheck`, and migrating into a function with RAI checks and status checks from the former `ActionAvailabilityCheck` object. 
This also maintains `actions.ts` and `planType.ts` as type-only files. It felt wrong to put functions in there. 
N/A

fix(package-actions): Consolidate package checks

---

src/services/ui/src/components/Opensearch/Filtering/FilterableSelect.tsx

On the Dashboard, the Submission Source select menu was overlapping with the CPOC select menu. This was caused by the  select menus' z-index being set to 50. Removing the z-index appears to resolve the issue.
https://qmacbis.atlassian.net/browse/OY2-26921
Removing the z-index allows the select menus to display as expected.

fix(dashboard): fix overlapping select menus

---

src/packages/shared-types/seatool.ts
src/packages/shared-types/statusHelper.ts
src/packages/shared-utils/package-actions/getAvailableActions.ts
src/packages/shared-utils/package-actions/rules.ts
src/packages/shared-utils/packageCheck.ts
src/services/api/handlers/getPackageActions.ts
src/services/ui/src/pages/actions/WithdrawPackage.tsx
src/services/ui/src/pages/detail/index.tsx

The intent of this PR address multiple bug fixes. 
1. Drop the `2nd Clock` status down to a separate line from the sub status . 
2. Make changes to ensure `HELPDESK` UsersRole and `CMS_READ_ONLY` roles do not have access to take actions on packages. 
3. Implement a change to add `Withdraw Package` action for state users after an RAI as been issued 
https://qmacbis.atlassian.net/browse/OY2-26876
https://qmacbis.atlassian.net/browse/OY2-26873
https://qmacbis.atlassian.net/browse/OY2-26875
1. I added ml-2 class to give space between substatus and the 2nd clock as we currently only have one substatus 
2. here i am using the `!isCmsReadonlyUser(user)` In all the checks, as we do not want any action for read-only user.
3. Here i used the same checks From `arRespondToRai` in the …

"fix(bugs): disable actions for help desk, drop 2nd clock, add withdraw package when RAI is issued"

---

src/services/api/layers/ABP3/v1.ts
src/services/ui/src/components/RHF/Document.tsx
src/services/ui/src/components/Webform/footer.tsx
src/services/ui/src/components/Webform/index.tsx

Adds v1 of the ABP 3 webform to OneMAC (Mako).
https://qmacbis.atlassian.net/browse/OY2-26327
Test link: https://d268ha2bu9uwx3.cloudfront.net/
I added a `v1.ts` file for ABP 3, modeled after the existing `v1.ts` for ABP 1.

feat(ABP 3) Adds ABP 3 form to OneMAC (Mako)

---

src/services/ui/src/components/RHF/dependencyWrapper.tsx

DependencyWrapper wraps the options in a rendered checkbox, but was pulling in a RHF hook into a non-form context. This adds a layer to prevent that in those cases.

fix(checkbox): using formContext hook outside of forms

---

src/services/ui/src/api/mocks/item.ts
src/services/ui/src/api/useGetItem.test.ts
src/services/ui/src/api/useGetItem.ts
src/services/ui/src/utils/zod.ts

This fixes a bug where you could Renew/Amend a Waiver Amendment. Only initial waivers and renewal waivers are renewable/amendable.
https://qmacbis.atlassian.net/browse/OY2-27691
Added a helper func to `useGetItem.ts` and tested accordingly
Because `getItem` only takes an ID, we have to pipe custom value overrides thru test ids, such as `existing-approved-actionType=Amend`. I set up the tool to make this happen for any key in the `Document` type meaning anything can be customized so long as we plug it into the response body.

fix(waivers): only allow Renewal and Initial waiver ids for Renew/Amend actions

---

.gitignore
src/cli/runner.ts
yarn.lock

Fix most of our snyk code findings.
Closes https://qmacbis.atlassian.net/browse/OY2-26799
The majority of our findings were around unsanitized input being executed.  This fixes that.
This also fixes an issue with the follow-redirects package.
There is an outstanding issue with serverless-running-stages that cannot be fixed, and also with serverless-step-functions.  As both of these are not deployed to the application, and just used in deployment, I suggest we ignore them.
N/A

fix(snyk code):  Sanitize some input to fix a snyk finding

---

src/services/api/webforms/ABP1/v202401.ts
src/services/api/webforms/ABP1/v202402.ts
src/services/api/webforms/ABP2A/v202401.ts
src/services/api/webforms/ABP2B/v202401.ts
src/services/api/webforms/ABP3/v202401.ts
src/services/api/webforms/ABP3_1/v202401.ts
src/services/api/webforms/ABP5/v202401.ts
src/services/ui/src/components/Inputs/input.tsx
src/services/ui/src/components/RHF/utils/validator.ts

Previously, a user could enter a single space into an input field and the validator would consider it valid. To avoid this, we will use regex on the input fields to prevent a user from entering text with leading or trailing whitespace.
https://qmacbis.atlassian.net/browse/OY2-27908

fix(webforms): Don't allow leading or trailing whitespace in input fields

---

src/services/api/webforms/ABP1/v202401.ts
src/services/api/webforms/ABP1/v202402.ts
src/services/api/webforms/ABP5/v202401.ts

Previously, when a user added `0` as a value to a numeric-only input field, validation would fail. Instead, we would like users to have the option to enter `0` as a valid value. This PR changes the validation regex to allow this.
https://qmacbis.atlassian.net/browse/OY2-28085
The validation regex was changed from `/^[1-9]\d*$/` to `/^[0-9]\d*$/`.

feat(webforms): Allow zero as a value in numeric input fields

---

src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx

Added FAQ link footer for Temporary Extension form.
https://qmacbis.atlassian.net/browse/OY2-27896
_How does this change address the issue?_

fix(OY2-27896): temporary extension faq footer

---

src/packages/shared-types/forms.ts
src/services/api/webforms/ABP2A/v202401.ts
src/services/api/webforms/ABP2B/v202401.ts
src/services/ui/src/components/Inputs/checkbox.tsx
src/services/ui/src/components/RHF/Slot.tsx
src/services/ui/src/components/RHF/SlotField.tsx

Logic was added to allow styledLabel or label for checkboxes. Before an empty string would populate, but we now added a check to fall back on either styleLabel or label if it is an empty string

fix (checkbox label logic): add fix to label and styled label logic

---

src/services/ui/src/components/RHF/SlotField.tsx

Add fix for ParentId in RHFSlot. We were missing a property that was causing radio buttons and checkboxes from receiving a concatenated parentId string.

fix(fix parentId in RHF): add ParentID to fix rhfSlot

---

src/packages/shared-types/forms.ts
src/packages/shared-types/inputs.ts
src/services/ui/src/components/Inputs/index.tsx
src/services/ui/src/components/Inputs/multiselect.tsx
src/services/ui/src/components/RHF/SlotField.tsx
src/services/ui/src/components/RHF/tests/SlotField.test.tsx
src/services/ui/src/components/RHF/utils/initializer.ts

This adds the Multiselect component from the Dashboard to an RHF component that can be used in webforms.
https://qmacbis.atlassian.net/browse/OY2-28491
I wrapped the `react-select` component into its own component that can be used with RHF and our webforms. This should make it available for use in upcoming webforms.

feat(webforms): Multiselect

---

src/services/auth/libs/users.json
src/services/email/handlers/processEmails.tsx
src/services/email/libs/data-lib.js

>Mako - Files section in Submission emails for all package types shows wrong file type. It appears the file type name being displayed is a backend name version but should display the more user friendly version. This was working as intended back in April and started showing the backend file types in May.
[OY2-28880](https://qmacbis.atlassian.net/browse/OY2-28880)
- using the attachment title map from attachements.ts so that it matches what is displayed in the app
Here are some examples of the new attachment titles:
1915(c) Waiver submitted to spa@cms.hhs.gov
CHIP SPA Submitted to spa@cms.hhs.gov
Medicaid SPA Submitted to spa@cms.hhs.gov

fix(email): Files section in Submission emails for all package types shows wrong file name type

---

src/services/ui/src/components/Form/content/ContentWrappers.tsx
src/services/ui/src/features/package-actions/ActionForm.tsx
src/services/ui/src/features/package-actions/lib/modules/toggle-rai-withdraw/index.tsx
src/services/ui/src/features/package-actions/lib/schemaSwitch.ts

Remove validation warnings from forms without inputs
https://qmacbis.atlassian.net/browse/OY2-28620
The previous iteration didn't account for two things:
- empty zod object schemas were still technically schemas and could be tested against
- displaying form warnings when there weren't inputs
This PR adds a new schema type: `null`. `null` means there are no input validation rules to be tested. We can check whether `setup.schema` is `null` and hide validation warnings.

fix(ui):remove unnecessary warnings from forms without inputs

---

src/services/api/webforms/ABP4/v202401.ts

There was an unintended gap between the select menu and upload box, two child elements under the same parent:
This PR eliminates that gap between the two elements. The other two items listed in the ticket (a thicker border around the upload box and the height of the text area set to 76 px) have already been resolved in other tickets.
https://qmacbis.atlassian.net/browse/OY2-28876
This was resolved by leveraging the `WrappedGroup` RHF component and editing the inline Tailwind CSS properties in the ABP-4 webform file.

fix(apb4-changes): Resolve gap between two child elements

---

src/services/ui/src/components/Opensearch/main/Filtering/Drawer/hooks.ts

CPOC names of various cases weren't sorted according to their alphabetical order
https://qmacbis.atlassian.net/browse/OY2-26746
- check the commit message for more information

fix(ui): add `Intl.Collator("en").compare` to sort CPOC names alphabetically

---

src/services/ui/package.json
yarn.lock

#644 introduces a new bug – having periods in the URL breaks vite's redirect to `index.html`, so it always served a `404` if a user navigated directly to `/details/1915(b)/OH-1996.R00.00`
Version 5 fixes this [bug](https://vitejs.dev/guide/migration.html#allow-path-containing-to-fallback-to-index-html). 
**Reference**: [v5 changelog](https://vitejs.dev/guide/migration.html)
- Learning moment for sure: whenever a route is updated, we should test whether or not navigating directly to the URL works

chore(ui): update `vite`

---

src/services/email/libs/bundle-lib.js
src/services/email/ses-email-templates/index.js

All other emails were confirmed to be working except the 1915(c). This will fix 1915(c) emails for withdraw package and respond to rai.
https://d28t56r6aj173b.cloudfront.net/
1915c was not falling into an logic path. I therefore made the 1915b emails more generic in order to also work for the 1915c package withdraw and 1915c respond to rai
1915c Package Withdraw CMS
1915c Package Withdraw State
1915c RAI Response CMS
1915c RAI Response State

Oy2 28892 - fix 1915(c) emails

---

src/services/ui/src/components/Opensearch/main/Filtering/Drawer/consts.ts
src/services/ui/src/features/dashboard/Lists/spas/consts.tsx
src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
src/services/ui/src/features/package/package-details/hooks.tsx

Update `Formal RAI Received` to `Formal RAI Response` with capitalization differing in labels
https://qmacbis.atlassian.net/browse/OY2-29214
- text updates make the world go round

feat(ui): update Formal RAI-centric labels

---

src/services/ui/src/components/Form/content/ContentWrappers.tsx
src/services/ui/src/components/Form/old-content.tsx
src/services/ui/src/features/submission/app-k/index.tsx
src/services/ui/src/utils/zod.ts

The purpose of this PR is to change the text in app-k forms to line up more accurately with what is in the legacy application.
https://qmacbis.atlassian.net/browse/OY2-28381

fix(text-changes-appk): Fix the language in app-k forms to match legacy application

---

eslint.config.mjs
react-app/src/components/Form/content/ContentWrappers.tsx
react-app/src/components/Layout/index.tsx
react-app/src/components/Opensearch/main/Filtering/Drawer/index.tsx
react-app/src/components/RHF/RHFTextDisplay.tsx
react-app/src/components/RHF/Section.tsx
react-app/src/components/UsaBanner/index.tsx
react-app/src/features/dashboard/Lists/renderCells/index.tsx
react-app/src/features/faq/content/oneMACFAQContent.tsx
react-app/src/features/package-actions/ActionForm.tsx
react-app/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
react-app/src/features/package/admin-changes/index.tsx
react-app/src/features/package/package-details/appk.tsx
react-app/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
react-app/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
react-app/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
react-app/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
react-app/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
react-app/src/features/submission/waiver/shared-components/SubmitAndCancelBtnSection.tsx

A bug I introduced in #663. I added `id` as a default value, and that meant any record with an `id` field was populated with that value.
https://qmacbis.atlassian.net/browse/OY2-29532
- conditionally add `id` if `actionType === 'update-id'`
- remove all instances of `Missing or malformed information. Please see errors above.`. QE said that it's an unused element of older form logic and was no longer needed.
- add new eslint rule: [no-useless-jsx-fragment rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md) that will error out when we use fragments with one child:
```tsx
<>
<span>
hello world
</span>
</>
```
- adjusted code that errored out

fix(ui): Fix TE prefilled with waiver ID

---

lib/libs/webforms/ABP8/sections/v202401.ts

ABP 8 was still using one instance of the deprecated FieldGroup. This replaces it with FieldArray.

bug(webform): Replace deprecated FieldGroup with FieldArray

---

react-app/src/components/RHF/SlotField.tsx

Add logic to successfully set date within a slot field. In turn ABP8 dates should now have the ability to be saved/set and appear on page load with saved data.
https://qmacbis.atlassian.net/browse/OY2-29679

fix(daypicker functionality) fix daypicker to successfully set date in slot field

---

react-app/src/components/Layout/index.tsx
react-app/src/components/UsaBanner/index.tsx
test/e2e/pages/home.page.ts
test/e2e/pages/index.ts
test/e2e/pages/loginPage.ts
test/e2e/playwright.config.ts
test/e2e/tests/home/faq.spec.ts
test/e2e/tests/home/index.spec.ts
test/e2e/tests/home/noauth.spec.ts
test/e2e/utils/auth.setup.ts

_Describe the problem or feature in addition to a link to the issues._
_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_
_How does this change address the issue?_

Playwright build out

---

react-app/src/components/RHF/tests/additionalRules.test.ts
react-app/src/components/RHF/utils/additionalRules.ts

This PR updates the `noGapsOrOverlaps` validation rule based on [HCD feedback](https://qmacbis.atlassian.net/browse/OY2-30287).
* When age range 1 was 0-2 and age range 2 was 3-4, this was **not** considered a gap.
* When age range 2 was 0-2 and age range 2 was 2-4, this **was** considered an overlap.
* **Overlap rule changed:** When age range 1 is 0-2 and age range 2 is 2-4, this is **no longer considered an overlap.**
* **Gap rule changed:** When age range 1 is 0-2 and age range 2 is 3-4, this is **now considered a gap.**
Closes [OY2-30287](https://qmacbis.atlassian.net/browse/OY2-30287)
The change was made by adjusting the `noGapsOrOverlaps` validation rule in `additionalRules.ts`.

fix(webform): Adjust noGapsOrOverlaps validation per feedback

---

react-app/src/components/Pagination/Pagination.test.tsx
react-app/src/components/Pagination/index.tsx

Ticket outlines to add testing for the following:
- Pagination
- Accordion 
- Alert
But at the time of this PR Accordion and Alert had reported coverage of 100%, so this ticket is only adding tests for Accordion.
[OY2-29636] (https://jiraent.cms.gov/browse/OY2-29636)
- Created a test file for this component
- Added tests to check buttons were disabled when they should be based on passed down props
- Added tests to confirm call back functions were called when expected (again based on props) 
- Lastly added small check to ensure that if more than 10,000 records are passed in, the text will only read "of 10,000 records" - specifically added based on coverage report

feat(test): Tests for Pagination

---

react-app/src/utils/user.test.ts
react-app/src/utils/zod.test.ts

This PR adds unit test coverage for the Zod (`zod.ts`) and User (`user.ts`) utilities.
https://jiraent.cms.gov/browse/OY2-29714
Creates new test files and provides test coverage for each utility. Brings unit test coverage of each to 100%.

feat(unit tests): Zod and User utils

---

react-app/src/utils/crumbs.test.ts
react-app/src/utils/date.ts
react-app/src/utils/formOrigin.test.ts
react-app/src/utils/index.ts
react-app/src/utils/stateName.test.ts
react-app/src/utils/textHelpers.test.ts

The importance of testing our code goes without saying. At the time we were moving fast and “breaking” things so to speak, but now in an effort to really mature MAKO and start to prepare for production we would like to improve not only test coverage but also the general stability of our code.
A lot of our newer code has unit tests built in, but that leaves some of the older rough edges to be tested. The fact of the matter is we are still developing against this older cold and in doing so it can be quite flaky. We would like to take the first step and unit test the building blocks to confidently grow the code base into the future.
The following utils should pass unit testing. The complexity is identified in the title of the story.
createContextProvider
crumbs
date (file can be removed) …

feat(tests): utils

---

react-app/src/components/BreadCrumb/create-breadcrumbs.ts
react-app/src/features/selection-flow/external-landing/ExternalAppLandingPage.tsx
react-app/src/features/selection-flow/options.tsx
react-app/src/router.tsx
test/e2e/tests/a11y/index.spec.ts

All card choices and links that previously redirected users to MMDL for Medicaid ABP, Premiums and Cost Sharing; and CHIP Eligibility submissions are removed. (reference figma)
Verify that users can access all other card choices, and they continue to work as expected. 
Given that I am a Developer, When a user navigates to a Medicaid or CHIP SPA in Mako, the card choices that redirect the user to the MMDL system must be removed.

feat(ui): Remove MMDL Card Choices in Mako

---

lib/libs/email/content/withdrawPackage/emailTemplates/WaiverCMS.tsx
lib/libs/email/content/withdrawPackage/emailTemplates/WaiverState.tsx

Waiver Email Templates
https://jiraent.cms.gov/browse/OY2-31124

feat(ui): create waiver emails

---

react-app/src/features/faq/content/abpTemplate.tsx

https://github.com/Enterprise-CMCS/macpro-mako/pull/887
https://jiraent.cms.gov/browse/OY2-29929
Add links to the FAQ page to the corresponding MMDL template. (reference google drive folder)
Links should be ordered and worded like in the HCD figma
When clicked, the pdf template should open in a new tab
Given I am a Mako user, When I navigate to the FAQ page, Then I should be able to click the MMDL templates and view the template in a new tab.
Dev Note: The document names use the same title as the question/header on the FAQ page. For example, if the section header is "ABP 1: Alternative Benefit Plan Populations", then document on the google drive named "IG_ABP1_AlternativeBenefitPlanPopulations.doc" should be attached to that FAQ link.
Google Folder with MMDL Templates: …

fix(ui): removed guide under ABP section

---

react-app/src/features/faq/content/abpTemplate.tsx

https://github.com/Enterprise-CMCS/macpro-mako/pull/887
https://jiraent.cms.gov/browse/OY2-29929
Add links to the FAQ page to the corresponding MMDL template. (reference google drive folder)
Links should be ordered and worded like in the HCD figma
When clicked, the pdf template should open in a new tab
Given I am a Mako user, When I navigate to the FAQ page, Then I should be able to click the MMDL templates and view the template in a new tab.
Dev Note: The document names use the same title as the question/header on the FAQ page. For example, if the section header is "ABP 1: Alternative Benefit Plan Populations", then document on the google drive named "IG_ABP1_AlternativeBenefitPlanPopulations.doc" should be attached to that FAQ link.
Google Folder with MMDL Templates: …

fix(ui): added subtext to pdf links

---

eslint.config.mjs

Sometimes, it'd be nice to exclude certain properties from destructuring and not use them. This PR adds an exception for variables starting with `_`
- lint rule change

feat(workspace): allow vars with _ to be excluded from eslint rule

---

react-app/src/features/package/package-details/hooks.tsx
react-app/src/features/package/package-details/index.tsx

[Remove "Type" and "Subtype" fields from the State View on the Package Details Page](https://jiraent.cms.gov/browse/OY2-30981)
Adjust conditions to prevent `Type`/`Subtype` from being displayed to state users

feat(ui): remove ability for state users to view type/subtype

---

lib/libs/email/preview/WithdrawConfirmation/State/Waiver.tsx

https://jiraent.cms.gov/browse/OY2-31440
Add logic to preview withdraw waiver confirmation emails for state users. Previous template logic was created by Andie in another ticket.

feat(withdraw-waiver-confirmation): Add logic to preview withdraw waiver confirmation emails

---

react-app/src/components/ActionForm/index.tsx
react-app/src/components/Banner/banner.tsx

[OY2-32046](https://jiraent.cms.gov/browse/OY2-32046)
- remove `setTimeout` band-aids from previous fix
- adjust logic to monitor before/after pathname values

fix(ui): address banner not showing up on package actions page

---

lib/lambda/setupIndex.test.ts

Rework `setupIndex` test to avoid skipping

fix(test): attempt to fix `setupIndex` test

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/opensearch/main/transforms/app-k.ts
lib/packages/shared-types/opensearch/main/transforms/capitated-amendment.ts
lib/packages/shared-types/opensearch/main/transforms/capitated-initial.ts
lib/packages/shared-types/opensearch/main/transforms/capitated-renewal.ts
lib/packages/shared-types/opensearch/main/transforms/contracting-amendment.ts
lib/packages/shared-types/opensearch/main/transforms/contracting-initial.ts
lib/packages/shared-types/opensearch/main/transforms/contracting-renewal.ts
lib/packages/shared-types/opensearch/main/transforms/new-chip-submission.ts
lib/packages/shared-types/opensearch/main/transforms/new-medicaid-submission.ts
lib/packages/shared-types/opensearch/main/transforms/temporary-extension.ts

[OY2-31064](https://jiraent.cms.gov/browse/OY2-31064)
With bidirectional Seatool no longer a concern, this PR removes the logic determining the intial submission date, which maintained consistency 
- remove the `nextBusinessDayEpoch` variable and adjust conditional logic

fix(schema): remove logic for determining next business day for `submissionDate`

---

lib/lambda/processEmailsHandlers.test.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-32115)
Added some new test that will give coverage to a bunch of our index.ts files for our emails.  Improving our handler test.

feat(test) Email handler test

---

lib/lambda/search.test.ts
lib/lambda/update/updatePackage.test.ts
lib/lambda/update/updatePackage.ts
mocks/data/items.ts

[](https://jiraent.cms.gov/browse/OY2-32292)
Adding unit test coverage for the update lambda
Removed some unhittable exceptions we were doing.  Since the zod object was verifying fields there was just a couple things not matter what you couldn't hit.
I also refactored some code by moving it around a little to make sure we are returning the values we want to in some cases.

feat(test) Unit test for updating pacakges

---

.github/workflows/deploy.yml

Upload artifact on github actions is deprecated at v3.  putting to v4

feat(bug) update artifact update

---

react-app/src/features/faq/content/oneMACFAQContent.tsx

https://jiraent.cms.gov/browse/OY2-31827?filter=-1
1. Add the word "Letter" to the "Waiver RAI Response" title on the FAQ page. (reference screenshot)
Enter the URL and click on FAQ tab.
Expand the section - What are the attachments for a 1915(b) Waiver and 1915(c) Appendix K response to Request for Additional Information (RAI)?
Attachment type displayed as "Waiver RAI Response*" instead of "Waiver RAI Response Letter*".

fix(ui): Replace Response with Letter

---

lib/local-constructs/cloudwatch-to-s3/index.test.ts
lib/local-constructs/cloudwatch-to-s3/index.ts

[Ticket to close](https://jiraent.cms.gov/browse/OY2-32301)
The log says there was an explicit deny rule for log creation.
I created an explicit allow on the cloudwatch resource policy

fix(cloudwatch-role): allow log group creation for firehose role

---

react-app/src/components/RHF/dependencyWrapper.tsx
react-app/src/components/RHF/dependencyWrappterFunction.test.tsx
react-app/src/components/RHF/tests/depedencyWrapper.test.tsx

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-32532)
Additional unit test for the dependency wrapper.  One is for the functions and paths, one is for the rendering.
Changed a function to become an export for testing purposes.

feat(test) dependency wrapper test

---

react-app/src/components/ActionForm/index.tsx
react-app/src/features/forms/post-submission/upload-subsequent-documents/index.tsx

[OY2-32247](https://jiraent.cms.gov/browse/OY2-32247)
We needed to overwrite the previous schema with an optional value to hide the schema's attachments property's respective errors. This also meant the `files` property needed an update allowing us to access those properties in a type-safe way.
- some fancy zod manipulation
https://github.com/user-attachments/assets/ca45dfd8-f93e-4d64-8e9b-63d47b1ec280

fix(ui): hide errors for individual files when uploading subsequent docs

---

lib/lambda/search.test.ts
mocks/data/items.ts
react-app/src/api/useGetPackageActions.test.ts
react-app/src/features/forms/waiver/temporary-extension/temporary-extension.test.tsx

In my split spa ticket, I would like to use the mock Medicaid SPA item in my unit tests. However when using it I found that the mock item has the wrong ID format.
Another mock data item has been added to represent a Medicaid SPA item. The authority of the previous mock item has been updated to match the ID based on its format.  Any tests that were referring to this ID were modified accordingly.

fix(mocks): Edit SPA mock item ID format

---

react-app/src/components/Opensearch/main/Filtering/Drawer/consts.ts
react-app/src/components/Opensearch/main/Filtering/Drawer/hooks.ts

[OY2-32376](https://jiraent.cms.gov/browse/OY2-32376)
- remove pertinent UI logic

chore(ui): remove `Intake Needed` from Filters

---

lib/lambda/processEmails.ts
lib/libs/email/content/withdrawPackage/index.tsx

https://jiraent.cms.gov/browse/OY2-31139
Added logic to send emails in templates to the correct email groups

fix(all-state-emails): Add logic to include all state emails in templates

---

lib/libs/email/content/email-components.tsx
lib/libs/email/content/withdrawRai/emailTemplates/ChipSPAState.tsx
lib/libs/email/content/withdrawRai/emailTemplates/WaiverCMS.tsx
lib/libs/email/content/withdrawRai/emailTemplates/WaiverState.tsx
lib/libs/email/content/withdrawRai/index.tsx
lib/libs/email/preview/InitialSubmissions/State/__snapshots__/InitialSubmissionState.test.tsx.snap
lib/libs/email/preview/RespondToRai/State/__snapshots__/ResToRaiState.test.tsx.snap
lib/libs/email/preview/WithdrawConfirmation/State/__snapshots__/WithdrawConfirmationState.test.tsx.snap
lib/libs/email/preview/WithdrawPackage/State/__snapshots__/WithdrawPackageState.test.tsx.snap
lib/stacks/auth.ts

https://jiraent.cms.gov/browse/OY2-32669
Fix code so that emails send to State user(s) when a Withdraw RAI Response package action for all waiver types is submitted.
Fix code so that emails send to CMS user(s) when a Withdraw RAI Response package action for all waiver types is submitted. 
Confirm the email templates match the content on the confluence page: https://confluenceent.cms.gov/display/MACPRO3/Email+Notifications+for+Package+Actions

fix(ui): Email in VAL

---

lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/AppKCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/AppKState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/ChipSpaCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/ChipSpaState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/MedSpaCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/MedSpaState.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/Waiver1915BCMS.tsx
lib/libs/email/content/uploadSubsequentDocuments/emailTemplates/Waiver1915BState.tsx
lib/libs/email/content/uploadSubsequentDocuments/index.tsx
lib/libs/email/preview/UploadSubsequentDocuments/State/CHIP_SPA.tsx
lib/libs/email/preview/UploadSubsequentDocuments/State/__snapshots__/UpSubDocState.test.tsx.snap
lib/packages/shared-types/events/upload-subsequent-documents.ts
mocks/data/submit/changelog.ts
react-app/src/features/forms/post-submission/upload-subsequent-documents/index.tsx

[OY2-33286](https://jiraent.cms.gov/browse/OY2-33286)
Emails work on the `authority` property, which determines the template from the email template map. Therefore, without sending the `authority` property when submitting the `upload-subsequent-documents` form, the email sending failed 
- add `authority` to `upload-subsequent-documents` schema
- add `authority` to the `defaultValues` prop in `ActionForm`

fix(emails): send `upload-subsequent-documents` emails

---

lib/libs/email/content/email-components.tsx
lib/libs/email/preview/InitialSubmissions/State/Waiver1915bContracting/Amendment.tsx
lib/libs/email/preview/InitialSubmissions/State/Waiver1915bContracting/Initial.tsx
lib/libs/email/preview/InitialSubmissions/State/Waiver1915bContracting/Renewal.tsx
lib/libs/email/preview/InitialSubmissions/State/__snapshots__/InitialSubmissionState.test.tsx.snap

[Ticket to close](https://jiraent.cms.gov/browse/OY2-32380)
* updates rendering of email templates to manually handle line breaks by converting them to `<br>` elements

feat(email): Handles additional information line breaks by converting them to <br> elements

---

lib/libs/email/content/newSubmission/emailTemplates/ChipSpaCMS.tsx
lib/libs/email/content/newSubmission/emailTemplates/ChipSpaState.tsx
lib/libs/email/content/newSubmission/emailTemplates/MedSpaState.tsx
lib/libs/email/preview/InitialSubmissions/CMS/__snapshots__/InitialSubmissionCMS.test.tsx.snap
lib/libs/email/preview/InitialSubmissions/State/__snapshots__/InitialSubmissionState.test.tsx.snap

https://jiraent.cms.gov/browse/OY2-33300?filter=-1
1. Add blue banner/footer to the Medicaid and CHIP SPA initial submission email notifications (displaying the CMS address)
Env - VAL
Login as a state user and submit a Medicaid SPA in mako.
Both State and CMS users should receive the notification.
Minor verbiage issue for the State user notification (everywhere we deleted that specific text but confluence still has this text for this notification

Fix(emails): fixed verbiage text for emails (MedSPA and ChipSPA)

---

lib/libs/email/content/respondToRai/index.tsx

https://jiraent.cms.gov/browse/OY2-32873
This PR addresses [feedback from the QA phase in Val](https://jiraent.cms.gov/browse/OY2-33446). Previously, Padma was seeing her email address duplicated in the "To" field. These changes aim to resolve that issue by filtering out the "To" email addresses from the "CC" array.
This will need to be tested on Val by Padma with her email address to confirm that the fix works.
Instead of looking for a string that exactly matches the email address, we filter out "CC" addresses that contain the "To" email address as a substring. This is because the email addresses are formatted in this format: "Firstname Lastname <email@address.com>".
By filtering out based on substring, we can skip any address lines that contain a duplicate email address, preventing …

fix(emails): filter out duplicate email addresses correctly

---

lib/libs/email/content/newSubmission/emailTemplates/ChipSpaCMS.tsx
lib/libs/email/preview/InitialSubmissions/CMS/__snapshots__/InitialSubmissionCMS.test.tsx.snap

https://jiraent.cms.gov/browse/OY2-33300?filter=-1
1. Add blue banner/footer to the Medicaid and CHIP SPA initial submission email notifications (displaying the CMS address)
removed spam line from cms new submission email

Fix(email): Footer missing and minor verbiage issue for Medicaid/CHIP SPAs initial submission notification.

---

react-app/src/features/faq/LegacyFaq.tsx

Tested Locally and in Feature branch to ensure that that the "uat-hide-mmdl-banner" launch darkly flag is working properly.

fix(ui) add back lines of code removed/overwritten during branch rebase

---

lib/packages/shared-types/events/contracting-renewal.ts
mocks/data/submit/changelog.ts

https://jiraent.cms.gov/browse/OY2-32392
Per QA feedback, there were two additional places where the upload components were out of order. Both places use `lib/packages/shared-types/events/contracting-renewal.ts` to determine this order, so the change was made there. `changelog.ts` was also updated with the change.

fix(forms): Reorder contract renewal upload fields

---

react-app/src/features/package/package-activity/index.test.tsx
react-app/src/features/package/package-activity/index.tsx

[OY2-33529](https://jiraent.cms.gov/browse/OY2-33529)
The download document button text in the package activity section should be changed from "Download all documents" to "Download all attachments"
"Document" has been changed to "attachment" and tests have been edited to accomodate for this change.

fix(ui): Update text on download attachment buttons

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/events/legacy-event.ts

Theory: Proposed Effective Date being capture causes issues during indexing into opensearch because this value is not always a date (sometimes it is "-- --") and this validation is already handled when we set it to proposedDate lower down in the transform.

fix(remove-proposed-effective-from-indexing): Remove proposedEffectiveDate as a value that gets captured in opensearch

---

react-app/src/api/useGetSystemNotifs.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-33741)
Whenever the top banner is closed  it breaks after it gets passed the first message.  this was due to an inconsistent data structure provided by the AWS secret that stored the value.  We are adding a type for notification in typescript and using a flat map to make it work with whatever data that comes in.
I'll add unit test for this in a different PR but this is a critical bug so getting this in fast matters more to me.

bug(fix): close banner bug

---

lib/packages/shared-types/notification.ts
mocks/handlers/api/notifications.ts
react-app/src/api/useGetSystemNotifs.ts

I put type safety on the banner system banner page to prevent unallowed objects to try to display on the banner.  So if the body is the wrong type or missing, the banner wont appear
Add a zod object and type checked text.

bug(update) Make strict for typing on banner objects

---

react-app/src/components/Inputs/upload.test.tsx
react-app/src/components/Inputs/upload.tsx
react-app/src/components/Inputs/uploadUtilities.test.ts
react-app/src/components/Inputs/uploadUtilities.ts
react-app/vitest.setup.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-33460)
Currently nothing prevents a user from uploading a file with the exact same file name causing issues when chips are deleted.  Logic is introduced to prevent the user from uploading files with the same name into a single react dropzone.
Logic was also changed for the error messages on when a file is too large or if it is a bad format.
upload.utilities was renamed to uploadUtilities for proper naming conventions.  The const within that file now throw exceptions as opposed to just throwing out happy responses in the event of failure.
Removed logic from ondrop and moved it to a custom validator to make sure files are correct.
By doing this there would have been duplicate error message since we have the react …

feat(ui) prevent files of same name

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/events/legacy-event.ts

[OY2-32338](https://jiraent.cms.gov/browse/OY2-32338)
https://d1ds2ig1a2kif1.cloudfront.net/
Some legacy dates that are missing are being ingested as epoch start date. This change is to update the ingestion of those dates such that they are null rather than the epoch start date
In the legacy transform of `LegacyEvent` add some logic to determine if the date is missing before converting to ISO date. This will prevent missing dates from being interpreted as 0 and tranformed to epoch start date.

fix(legacy): fixing legacy date ingestion logic such that empty dates are not interpreted as epoch start date

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/temporary-extension.ts

[OY2-33879](https://jiraent.cms.gov/browse/OY2-33879)
State was not being populated for Temporary Extension types. Causing these packages to not be available to the corresponding state users.
Updated the TE transform for legacy so that it no longer erases the state property and set custom statuses as TE is unique.

fix(lambda): legacy temporary extensions in mako

---

lib/lambda/sinkMainProcessors.test.ts
lib/packages/shared-types/events/legacy-event.ts

🎫 Linked Ticket
https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=6701&projectKey=OY2&view=planning&selectedIssue=OY2-33882&quickFilter=39527&issueLimit=100#
💬 Description / Notes
The RAI Response date field is empty in mako (might be because the Package Activity is empty) when compared to legacy

Fix(ui): fix RAI response date 

---

lib/packages/shared-types/events/legacy-event.ts

[Ticket to close](https://jiraent.cms.gov/browse/OY2-33881)
Setting `initialIntakeNeeded` to true at all times removes the subsequent documents action from appropriate packages. Fix checks to see if status is the expected status for sub docs. Left it as an array check in case of missed status states for the subsequent documents/initial intake status. As far as I can tell `SEATOOL_STATUS.PENDING` is the only status that needs this value to be false, but waiting on word from QA to be sure.

fix(legacy intake): upload subsequent document fix on legacy packages

---

lib/lambda/checkConsumerLag.ts
lib/lambda/sinkCpocs.test.ts
lib/libs/opensearch-lib.ts

The changes for admin stuff with legacy is causing ours tep functions to run forever because the lambda throws an exception acting like it doesnt process.  So not great.  Means we are getting CloudWatch logs run infinitely which means AWS is charging us a lot of money.  When the bulk update errors happen that throw is breaking stuff.  This also redoes the Comsumerlag to make a prettier report in AWS

Critical Bug: Cloudwatch run infinitely due to throw on bulk update with legacy.

---

react-app/src/features/package/package-details/details.tsx

[Ticket to close](https://jiraent.cms.gov/browse/OY2-33597)
Per CMS feedback during the demo on 3.10.25, CMS would like the text boxes for multi-line text fields (i.e. Type and Subtype) to be expanded. Possibly add bullet points to distinguish the selections. 
Current state
Proposed fix

fix(ui): expanding type and subtype textboxes

---

lib/lambda/search.test.ts
lib/lambda/sinkMainProcessors.test.ts
lib/lambda/sinkMainProcessors.ts
mocks/data/items.ts

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-33871)
This is to prevent RAI withdrawal request to not disappear.  Only works for non-legacy
Expanded on the functionality of checking placeholder statuses.  After it is in a pending rai withdrawal status only terminal statuses(withdrawn, terminated, or disapproved) can overwrite it.  Any other status that is not Pending-RAI will prevent it from changing as far as seatool is concerned.  
https://jiraent.cms.gov/secure/attachment/1484516/PlaceHolderFlow.drawio.pdf

rai withdrawal placeholder fix

---

lib/packages/shared-types/opensearch/changelog/index.ts
lib/packages/shared-types/opensearch/changelog/transforms/legacy-event.ts
lib/packages/shared-utils/legacy-event-type.test.ts
lib/packages/shared-utils/legacy-event-type.ts
react-app/src/features/package/package-activity/index.tsx

[OY2-33820](https://jiraent.cms.gov/browse/OY2-33820)
Originally the legacy items were imported under distinct legacy event types. This worked fine for importing and display but impacted the ability to do a subsequent submission action as that aciton relies on the original event type in order to determine what attachments are allowed on the subsequent submission form. Therefore this change will determine the legacy type and translate to the mako event type. Due to this the legacy event type was removed as it is no longer needed/used.
- Updated legacy changelog ingestion logic to determine appropriate mako event type
- Removed usage of new-legacy-submission event type

feat(api): revamp how we set legacy event types so that subsequent submission works

---

lib/lambda/sinkChangelog.ts
lib/packages/shared-types/opensearch/changelog/transforms/legacy-admin-change.ts

[OY2-34452](https://jiraent.cms.gov/browse/OY2-34452)
Reworked how legacy admin changes are processed and stored from kafka. 2 real changes:
1. sinkChangelog.ts - Instead of reading from package record read only the event records
2. legacyAdminChange.ts - Dont use the kafka event id for the record prefix, use the package id

fix: alter how legacy admin changes are processed from kafka

---

react-app/src/components/Tabs/index.tsx
react-app/src/features/dashboard/Lists/renderCells/index.tsx
react-app/src/features/dashboard/Lists/spas/consts.tsx
react-app/src/features/dashboard/Lists/spas/index.test.tsx
react-app/src/features/dashboard/Lists/waivers/consts.tsx
react-app/src/features/dashboard/Lists/waivers/index.test.tsx
react-app/src/utils/test-helpers/dashboard.tsx

This will resolve an issue where the timestamps were displaying inconsistantly between the dashboard and the package details page for record if the submission of a record was after 8 eastern
Ticket to Close:
https://jiraent.cms.gov/browse/OY2-34506

fix(timestamps-in-dashboard-to-et): change times in dashboard to et

---

react-app/src/components/Opensearch/main/Settings/Visibility.tsx

VoiceOver didn't announce the menu items names in Chrome (it worked in Safari and Firefox), so moving the label to the interactive element solves that issue

fix(ui): fix menu item voiceover for Chrome

---

react-app/src/components/Opensearch/main/Settings/Visibility.tsx

- Chrome isn't announcing the changes correctly, so moving the announcement attribute closer to the element seems to do the trick

chore(ui): move aria-live="polite" to button element

---

react-app/src/features/package/package-status/index.tsx

[[Ticket to close](link-to-ticket)](https://jiraent.cms.gov/browse/OY2-34661)
Secondclock status is not appearing for Pending Occurence or Pending approval.  Logic on the front end for some reason excluded it.  We already calculate the secondclock stuff on the backend for the package in the processor with:
`const isInSecondClock = (
raiReceivedDate: any,
raiWithdrawnDate: any,
seatoolStatus: any,
authority: any,
) => {
if (
authority !== "CHIP SPA" && // if it's not a chip
[
SEATOOL_STATUS.PENDING,
SEATOOL_STATUS.PENDING_CONCURRENCE,
SEATOOL_STATUS.PENDING_APPROVAL,
].includes(seatoolStatus) && // if it's in pending
raiReceivedDate // if its latest rai has a received date
) {
return true; // then we're in second clock
}
return false; // otherwise, we're not
};`
Just removed the bad logic …

Second clock not display

---

react-app/src/features/profile/me/index.tsx
react-app/src/features/sign-up/stateSignup.test.tsx
react-app/src/features/sign-up/stateSignup.tsx
react-app/src/hooks/useAvailableStates.ts

[OY2-34772](https://jiraent.cms.gov/browse/OY2-34772)
In the states dropdown, we are filtering any revoked/pending state regardless of the role. If a state submitter has access to a state and requested a role change of a state system admin, they would not see the state(s) they have access to.
If a state submitter requests to be a state system admin, they will now see all states.

fix(user-roles): Show all states for state signup

---

lib/lambda/user-management/userManagementService.test.ts
lib/lambda/user-management/userManagementService.ts

[OY2-34923](https://jiraent.cms.gov/browse/OY2-34923)
In VAL, some users with an underscore in their email came up as unknown in the User Management page. 
The request to return the user roles with their full names is now referencing the email object directly instead of trying to parse id.

fix(user-roles): Unknown full name for emails with underscore

---

lib/lambda/user-management/getRoleRequests.test.ts
lib/lambda/user-management/getRoleRequests.ts

[OY2-34756](https://jiraent.cms.gov/browse/OY2-34756)
- State system admins are only allowed to see and update state submitters within their territory in the User Management page.
- CMS Role Approvers are only allowed to see and update state system admin requests in the User Management page.

fix(user-roles): User Management page views

---

lib/packages/shared-types/forms.ts
lib/packages/shared-types/opensearch/changelog/transforms/app-k.ts
lib/packages/shared-types/opensearch/changelog/transforms/capitated-amendment.ts
lib/packages/shared-types/opensearch/changelog/transforms/capitated-initial.ts
lib/packages/shared-types/opensearch/changelog/transforms/capitated-renewal.ts
lib/packages/shared-types/opensearch/changelog/transforms/contracting-amendment.ts
lib/packages/shared-types/opensearch/changelog/transforms/contracting-initial.ts
lib/packages/shared-types/opensearch/changelog/transforms/contracting-renewal.ts
lib/packages/shared-types/opensearch/changelog/transforms/new-chip-details-submission.ts
lib/packages/shared-types/opensearch/changelog/transforms/new-chip-submission.ts
lib/packages/shared-types/opensearch/changelog/transforms/new-medicaid-submission.ts
lib/packages/shared-types/opensearch/changelog/transforms/respond-to-rai.ts
lib/packages/shared-types/opensearch/changelog/transforms/temporary-extension.ts
lib/packages/shared-types/opensearch/changelog/transforms/toggle-withdraw-rai.ts
lib/packages/shared-types/opensearch/changelog/transforms/upload-subsequent-documents.ts
lib/packages/shared-types/opensearch/changelog/transforms/withdraw-package.ts
lib/packages/shared-types/opensearch/changelog/transforms/withdraw-rai.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/amendment-waiver.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/app-k.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/chip-spa.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/initial-waiver.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/medicaid-spa.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/rai-response.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/renewal-waiver.ts
lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/temporary-extension.ts
lib/packages/shared-types/opensearch/main/transforms/respond-to-rai.ts
lib/packages/shared-types/opensearch/main/transforms/withdraw-package.ts
lib/packages/shared-types/opensearch/main/transforms/withdraw-rai-response.ts

Importing from the package inside the package causes issues with tests sometimes. Updating them to reference by relative path.
- updated all imports of `shared-types` within `lib/packages/shared-types` to use relative path instead

chore(refactor): removing circular imports from `shared-types`

---

lib/packages/shared-types/opensearch/main/transforms/legacy-transforms/temporary-extension.ts
lib/packages/shared-types/opensearch/main/transforms/seatool.ts
lib/packages/shared-types/package.json
lib/packages/shared-utils/package.json
mocks/data/cpocs.ts
mocks/data/users/index.ts
mocks/handlers/aws/cloudFormation.ts
mocks/handlers/aws/cognito.ts
vitest.config.ts

Cleaning up a couple of smaller issues
- removed lodash from a transform
- merged imports
- added type module and explicity exports from shared-types and shared-utils
- added type to cpocs in mocks
- changed import name in cloudFormation in mocks
- change import of jwt in cognito mocks
- excluding all of `test/` from the vitest tests

chore(refactor): cleaning up imports

---

lib/libs/email/content/withdrawRai/index.tsx

https://jiraent.cms.gov/browse/OY2-35034
For medicaid SPA's removed CPOC SRT added all state users to the recipients, all other state recipients are correct
Verified that CPOC & SRT are not on the state list
Medicaid:
CHIP:
Waiver:

fix(emails): Medicaid Withdraw RAI emails state had wrong recipients 

---

react-app/src/components/Footer/Footer.test.tsx
react-app/src/components/Footer/index.tsx

https://jiraent.cms.gov/browse/OY2-34514
Login as a CMS Role approver.
Check for the grey bottom banner.
For the role approvers, additionally "User Management" tab should display.
Issue #1 : "User Management" tab missing on the grey bottom footer.
"statesystemadmin, cmsroleapprovers, helpdesk, CMSsystemadmin are the only ones that can see the user management page i believe"
Issue #2 - Make sure Dashboard tab does not appear on the grey bottom banner for the approver roles. (CMSroleapprovers, CMSsystemadmin)

feat(ui): User Management" tab missing on the grey bottom footer
